---
title: "R Notebook"
output: html_notebook
---

```{r}
library(Seurat)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(splatter)
library(reshape2)
library(pROC)
library(ggforce) 
library(limma)
library(tictoc)
library(foreach)
library(scales)
library(ggplot2)
library(ggpubr)
library(ggExtra)
library(cowplot)
library(scales)
# Some helper functions
# A modified version of pPerm function, will include different statistics for each permutation 
pPerm.stat<- function(cm, groups, perm.size = 1000,lfc.cutoff=0.1, n.cores=1){
  if (n.cores>1){
    message(paste("Running", perm.size, "permutation with", n.cores, "cores in parallel"))
  }else{
    message(paste("Running", perm.size, "permutation in sequential"))
  }
  logcounts.all <- lognormCounts(cm, log=TRUE, prior.count=0.5) 
  
  # permutate all.bct 
  all.bct <- factor(groups)
  my.cluster <- parallel::makeCluster(
    n.cores, 
    type = "PSOCK"
  )
  
  tic.clearlog()
  tic(paste(perm.size, "permutation total time"))
  doParallel::registerDoParallel(cl = my.cluster)
  join <- function(lst, ...) {
    lapply(seq_along(lst),
           function(i) c(lst[[i]], 
                         lapply(list(...), function(lst2) lst2[[i]])
           )
    )
  }
  result<-list(list(), list(), list(), list(), list())
  result <- foreach(i=1:perm.size, .combine='join', .multicombine=TRUE,
                  .init=list(list(), list(), list(), list(),list())) %dopar% {
    # permutate the all.bct only 
    all.bct.shuffled <- sample(all.bct, replace = FALSE, size =length(all.bct))
    
    # to do marker analysis using Limma way
    #########################
    # Limma DE framework written by Belinda Phipson
    design <- model.matrix(~0+all.bct.shuffled)
    colnames(design)[1:(length(levels(all.bct.shuffled)))] <- levels(all.bct.shuffled)
    mycont <- matrix(0,
                     ncol=length(levels(all.bct.shuffled)),
                     nrow=length(levels(all.bct.shuffled)))
    
    colnames(mycont)<-levels(all.bct.shuffled)
    diag(mycont)<-1
    mycont[upper.tri(mycont)]<- -1/(length(levels(all.bct.shuffled))-1)
    mycont[lower.tri(mycont)]<- -1/(length(levels(all.bct.shuffled))-1)
    
    # Fill out remaining rows with 0s
    zero.rows <- matrix(0,ncol=length(levels(all.bct.shuffled)),
                        nrow=(ncol(design)-length(levels(all.bct.shuffled)))
    )
    
    test <- rbind(mycont, zero.rows)
    fit <- limma::lmFit(logcounts.all,design)
    fit.cont <- limma::contrasts.fit(fit, contrasts=test)
    fit.cont.eb <- limma::eBayes(fit.cont,trend=TRUE,robust=TRUE)
    #########################
    table.g1 <- limma::topTable(fit.cont.eb,sort="none",number = nrow(fit.cont.eb), coef=1)
    table.g2 <- limma::topTable(fit.cont.eb,sort="none",number = nrow(fit.cont.eb), coef=2)
    
    # one-sided t statistic 
    os.t.stat <- fit.cont$coef/ fit.cont$stdev.unscaled / fit.cont$sigma
    
    ts.t.stat <- fit.cont$coef/ fit.cont$stdev.unscaled / fit.cont$sigma
    
    os.modt.stat<- fit.cont.eb$t
    
    # two-sided moderated t statistic 
    ts.modt.stat<- fit.cont.eb$t
    

    os.treatt.stat<- (fit.cont$coef - lfc.cutoff)/ fit.cont$stdev.unscaled / fit.cont$sigma
    

    treat.result<- limma::treat(fit.cont.eb, lfc=lfc.cutoff, trend=TRUE, robust = TRUE)
    ts.treatt.stat<- treat.result$t
    

    lfc.p.stat <- fit.cont$coef*(1-pt(fit.cont$coef/ fit.cont$stdev.unscaled / fit.cont$sigma,
                                      df = fit.cont$df.residual,lower.tail=FALSE))
    
    list(os.t.stat, os.modt.stat,os.treatt.stat, ts.modt.stat, lfc.p.stat)
    
  }
  toc(log=TRUE)
 
  for (i in 1:length(result)){
    result[[i]]<-simplify2array(result[[i]])
  }
 
  parallel::stopCluster(cl = my.cluster)
  return (list(os.t.stat =result[[1]], 
               os.modt.stat =result[[2]], 
               os.treatt.stat =result[[3]], 
               ts.modt.stat =result[[4]], 
               lfc.p.stat =result[[5]]))
}


# A slight modified version of runComparison function,
# take sim_perm_arrays as input instead of running real permutation 
runComparison.stat<-function(sim, perm.size, statistic = "os.t", sim_perm_arrays,
                             lfc.cutoff=0.1, n.cores=1, true.upreg, 
                             cyclic.normalise=FALSE){
  message(paste("Statistic = ", statistic))
  obs_res<- computeObservation(counts(sim), factor(sim$Group),
                       statistic= statistic, lfc.cutoff=lfc.cutoff)
  obs.stat<- obs_res$obs.stat
  obs.pval<- obs_res$obs.pval
  obs.pval<- as.data.frame(obs.pval)
  cell.types <-levels(factor(sim$Group))
  # permutation stats
  t.perm.array<- sim_perm_arrays
  # two-sided p
  if (substr(statistic,1,2) == "ts"){
    perm.pvals<-apply(expand.grid(x = 1:dim(counts(sim))[1], 
                                  y = 1:dim(t.perm.array)[2]), 1, 
                      function(r) (sum(abs(t.perm.array[r[1],r[2], ]) > abs(obs.stat[r[1],r[2]]))+1)/(perm.size+1) )
    
  }else{
    perm.pvals<-apply(expand.grid(x = 1:dim(counts(sim))[1], 
                                  y = 1:dim(t.perm.array)[2]), 1, 
                      function(r) (sum(t.perm.array[r[1],r[2], ] > obs.stat[r[1],r[2]])+1)/(perm.size+1) )
  }
  
  perm.pval<- matrix(perm.pvals, 
                     nrow=dim(counts(sim))[1], 
                     ncol = dim(t.perm.array)[2], 
                     byrow=FALSE)
  rownames(perm.pval) <- row.names(counts(sim))
  colnames(perm.pval) <- cell.types
  perm.pval.adj<- apply(perm.pval, 2, p.adjust, method="BH")
   

  perm.pval.adj<- as.data.frame(perm.pval.adj)
  rownames(perm.pval.adj) <- row.names(counts(sim))
  colnames(perm.pval.adj) <- cell.types
  
  obs.pval.adj<- apply(obs.pval, 2, p.adjust, method="BH")
  obs.pval.adj <- as.data.frame(obs.pval.adj)
  rownames(obs.pval.adj) <- row.names(counts(sim))
  colnames(obs.pval.adj) <- cell.types
  rownames(obs.pval) <- row.names(counts(sim))
  colnames(obs.pval) <-cell.types
  
  df.list=vector("list", length(cell.types))
  for (ct in 1: length(cell.types)){
    group.df<- obs_res$summary.tb[, c(ct, length(cell.types)+1)] 
    row.names(group.df)<-row.names(obs_res$summary.tb)
    df.list[[ct]] <-group.df
  }
  setNames(df.list, paste("group", 1:ct,".df",sep=""))
  for (i in 1:length(df.list)){
    df.list[[i]]$true.DE<- 0
    df.list[[i]][match(true.upreg[[i]],row.names(obs_res$summary.tb)), "true.DE"]<-1
    df.list[[i]]$limma.raw.pvalue <- obs.pval[,i]
    df.list[[i]]$limma.adj.pvalue <- obs.pval.adj[, i]
    df.list[[i]]$perm.raw.pvalue <- perm.pval[, i]
    df.list[[i]]$perm.adj.pvalue <- perm.pval.adj[, i]
  }
  
  return(list(result.table= df.list , obs.stat= obs.stat, 
              t.perm.array=t.perm.array,
              perm.pval = perm.pval, 
              perm.pval.adj=perm.pval.adj,
              obs.pval=obs.pval,
              obs.pval.adj=obs.pval.adj,
              true.upreg = true.upreg
  ))
}
```

```{r}


pbmc.data<- readRDS("pbmc_pooled_sex.Rds")
cm<- pbmc.data@assays$RNA@counts
table(pbmc.data$individual)

cm<- pbmc.data[, pbmc.data$individual == "689_690"]@assays$RNA@counts
dim(cm) 

pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)
cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]
ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep


# with one cell type from one individual
selected_cells <- colnames(cm.processed[,pbmc.data[,colnames(cm.processed)]$predicted.celltype.l1 =="CD4 T"])
cm.processed.r<- cm.processed[, match(selected_cells, colnames(cm.processed))]
metadata <- data.frame(cell_type = pbmc.data[row.names(cm.processed.r),colnames(cm.processed.r)]$predicted.celltype.l1,
                       ind = '689_690')

sce <- SingleCellExperiment(list(counts=as.matrix(cm.processed.r)),colData=metadata)


curr_params <- newSplatParams()
# estimate the parameter 
curr_params <- splatEstimate(sce,params = curr_params)
```


## Two Groups
### Background 
```{r}
groups_lst<- list(#c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )


set.seed(23098)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

set.seed(seed.number.cp[1])
rep.seed <- sample(x = seed.number.cp[1]:seed.number.cp[1]+93, 
                   size = length(groups_lst), replace = FALSE)
pl.PCA<-list()
num.df<- as.data.frame(matrix(0, nrow = 6*2, ncol = 3))
colnames(num.df)<-c("group","num.cells", "cp")
num.df$group<- rep(c("Group1","Group2"), each=6, times=1)

for (cp in 1:length(groups_lst)){
  sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                       batchCells = 1000, dropout.type = "none", out.prob = 0, 
                       de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                       group.prob = groups_lst[[cp]],
                       seed = rep.seed[cp], 
                       de.facLoc = c(1.1, 1.1),
                       de.facScale = c(0.5, 0.5),
                       verbose = FALSE
  )
  sim <- logNormCounts(sim)
  sim <- runPCA(sim)
  cell.prop<- paste(as.character(groups_lst[[cp]]*100),collapse=":")
  num.df[cp, 2:3]<- c(as.numeric(table(sim$Group)[1]),cell.prop)
  num.df[cp+6, 2:3]<-c(as.numeric(table(sim$Group)[2]),cell.prop)
}
gr<- unlist(groups_lst)*100

cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 2, length(gr))),   
                                FUN= paste, collapse='% : '), 1))
num.df$cp<-factor(num.df$cp)

num.df$formatedcp<- rep(paste(paste(cp.ft, "%",sep=""), sep=""))
num.df$formatedcp<- factor(num.df$formatedcp)
num.df$formatedcp<-factor(num.df$formatedcp, 
                 levels = c("5% : 95%","10% : 90%","20% : 80%",
                            "30% : 70%","40% : 60%","50% : 50%")
                 )
num.df$group<-factor(num.df$group)
num.df$num.cells<-as.numeric(num.df$num.cells)
num.cells<-ggplot(data = num.df, 
       aes(x = formatedcp, y = num.cells,fill =  group))+
  geom_bar(size=0.2, stat="identity",width=0.9)+
   theme(plot.title = element_text(size = 14, face = "bold"), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        legend.position="right"
        )+
  guides(fill = guide_legend(ncol = 1))+
  xlab("cell number proportions")+
  ylab("number of cells")+
  ggtitle("Number of cells in each simulation")
ggsave("num.cells.pdf", width = 8, height=6)

```

### Experiment 
50 repeated runs for each cell number proprotion split. I run 20 times firstly and save all the objects, followed by another 30 runs. 
```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )
# My random number setting
# 1:20 runs -> 20run_7cp_g22098_new
# set.seed(22098)
# rep.times<-20
# rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+8900, 
#                         size = length(groups_lst), replace = FALSE)
# 20:50 runs -> 30run_7cp_g23098_new
#set.seed(23098)
#rep.times<-30
#rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
#                         size = length(groups_lst), replace = FALSE)
set.seed(23098)
rep.times<-50
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  print(rep.seed)
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObservation(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
      obs_res<- computeObservation(counts(sim), factor(sim$Group), statistic= "os.t")
      DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
      DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    }
   
     message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-6
    #if (cp == 1){
    #  perm.size = 10000
    #}else{
    #  perm.size = 4000
    #}
    
    true.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    true.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    true.g1<- intersect(true.g1, row.names(sim))
    true.g2<- intersect(true.g2, row.names(sim))
    true.upreg = list("Group1" = true.g1, "Group2"=true.g2)
    
    perm.array.lst<- pPerm.stat(counts(sim), sim$Group, 
                                perm.size=perm.size, n.cores=n.cores)
    
    # generate perm & observation p-values for each stat 
    os.t.res<- runComparison.stat(sim, perm.size, statistic = "os.t", 
                                  sim_perm_arrays = perm.array.lst$os.t.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    os.modt.res<- runComparison.stat(sim, perm.size, statistic = "os.modt", 
                                  sim_perm_arrays = perm.array.lst$os.modt.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    lfc.p.res<-runComparison.stat(sim, perm.size, statistic = "lfc.p", 
                                  sim_perm_arrays = perm.array.lst$lfc.p.stat, 
                                  n.cores = n.cores, true.upreg = true.upreg)
    # save the result for each stat 
    # saveRDS(os.t.res, paste(prefix, "os.t.Rds", sep="."))
    #  saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    #  saveRDS(os.modt.res, paste(prefix, "os.modt.Rds", sep="."))
    
    # run= 1:20
    #os.t.res<- readRDS(paste(prefix, "os.t.Rds", sep="."))
    #lfc.p.res<- readRDS( paste(prefix, "lfc.p.Rds", sep="."))
    #os.modt.res<- readRDS(paste(prefix, "os.modt.Rds", sep="."))
    
    # run= 20:50
    # saveRDS(os.t.res, paste(prefix,"rep", 20+rep,"os.t.Rds", sep="."))
    #os.t.res<- readRDS(paste(prefix,"rep", 20+rep,"os.t.Rds", sep="."))
    #lfc.p.res<-readRDS(paste(prefix, "rep", 20+rep,"lfc.p.Rds", sep="."))
    # os.modt.res<-readRDS(paste(prefix, "rep", 20+rep,"os.modt.Rds", sep="."))
    ############################################################################
    # creat the result table 
    stat.lst<- c("os.t","lfc.p", "os.modt")
    res.lst<- list(os.t.res,lfc.p.res,os.modt.res)
    if (exists("adj.p.50run") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      adj.p.50run<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      #obs<- computeObs(counts(sim), factor(sim$Group),statistic= stat.lst[a])
      auc.values <- computeAUC(result=res.lst[[a]], markers =res.lst[[a]]$true.upreg)
      
      adj.df<- computeComparison(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                                       marker.genes=res.lst[[a]]$true.upreg, 
                                    ids = paste(paste(as.character(table(sim$Group)),
                                                      collapse="_"), rep.seed[cp], sep="_"),
                             cell_num=as.vector(table(sim$Group)), 
                             perm.size=10000, auc.values=auc.values,
                             statistic=stat.lst[a])
  
      adj.p.50run<- rbind(adj.p.50run, adj.df)
    
  
   
    }
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)


```

plots for ordinary t and moderated t statistic from 50 repeated runs 
```{r}
adj.p.50run[adj.p.50run$TP==0, c("sensitivity","precision","F1")]=0
adj.p.50run$category<- paste(adj.p.50run$test.name, adj.p.50run$statistic)
adj.p.50run$category<- gsub(adj.p.50run$category, pattern="os.t", replacement = "ordinary.t")
adj.p.50run$category<- gsub(adj.p.50run$category, pattern="os.modt", replacement = "moderated.t")
adj.p.50run$category<- gsub(adj.p.50run$category, pattern="lfc.p", replacement = "W")
gr<- unlist(groups_lst)*100

cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 2, length(gr))),   
                                FUN= paste, collapse='% : '), 1))
adj.p.50run$cp<- rep(paste("#Group1 : #Group2 = ",paste(cp.ft, "%",sep=""), sep=""),times=50,each = 12)
adj.p.50run$cp<-factor(adj.p.50run$cp, 
                 levels = c("#Group1 : #Group2 = 1% : 99%",
                            "#Group1 : #Group2 = 5% : 95%",
                            "#Group1 : #Group2 = 10% : 90%",
                            "#Group1 : #Group2 = 20% : 80%",
                            "#Group1 : #Group2 = 30% : 70%",
                            "#Group1 : #Group2 = 40% : 60%",
                            "#Group1 : #Group2 = 50% : 50%")
                 )
df<-adj.p.50run[adj.p.50run$category %in% c("limma ordinary.t","permutation ordinary.t"), ]

df<- adj.p.50run[adj.p.50run$cp %in% c("#Group1 : #Group2 = 1% : 99%"), ]

#df$category<- factor(df$category, levels=c("permutation ordinary.t", "permutation W"))
df$category<- factor(df$category, levels=c("limma ordinary.t","permutation ordinary.t", 
                                           "limma moderated.t","permutation moderated.t", 
                                           "permutation W"))
df<- df[df$cp %in% c("#Group1 : #Group2 = 5% : 95%",
                                 "#Group1 : #Group2 = 10% : 90%",
                                 "#Group1 : #Group2 = 20% : 80%",
                                 "#Group1 : #Group2 = 30% : 70%",
                                 "#Group1 : #Group2 = 40% : 60%",
                                 "#Group1 : #Group2 = 50% : 50%"),]
df$cp<- factor(df$cp, levels = c("#Group1 : #Group2 = 5% : 95%",
                                 "#Group1 : #Group2 = 10% : 90%",
                                 "#Group1 : #Group2 = 20% : 80%",
                                 "#Group1 : #Group2 = 30% : 70%",
                                 "#Group1 : #Group2 = 40% : 60%",
                                 "#Group1 : #Group2 = 50% : 50%"),
               labels = c("#Group1 : #Group2 \n = 5% : 95%",
                                 "#Group1 : #Group2 \n = 10% : 90%",
                                 "#Group1 : #Group2 \n = 20% : 80%",
                                 "#Group1 : #Group2 \n = 30% : 70%",
                                 "#Group1 : #Group2 \n = 40% : 60%",
                                 "#Group1 : #Group2 \n = 50% : 50%"))
clrs<-c('lightsteelblue2','navajowhite2')# ordinary t
#clrs<-c("steelblue2","darkgoldenrod1") # moderated t
#clrs<-c("navajowhite2", "green4") # W
clrs<- c('lightsteelblue2','navajowhite2', "steelblue2","darkgoldenrod1","green4")
sensitivity<-ggplot(data = df,
                    aes(x = factor(category), y = sensitivity,fill = factor(category)))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(axis.text.x = element_blank(), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)


precision<-ggplot(data = df,
                    aes(x = factor(category), y = precision,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size=10), 
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  ylab("precision")+ 
  #scale_x_discrete(labels=c("permutation \n ordinary.t","permutation \n W"))+
  scale_y_continuous(limits=c(0,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)

f1<-ggplot(data = df,
           aes(x = factor(category), y = F1,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(legend.title=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        axis.text.x = element_text(size=10), 
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=1, length(clrs)))+
  ylab("F1 score")+ 
  scale_y_continuous(limits=c(0,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)+
  scale_x_discrete(labels=c("limma \n ordinary.t","permutation \n ordinary.t"))
ggarrange(sensitivity, precision, ncol = 1,  nrow = 2,
          legend="none", common.legend = T,align="hv")
ggsave(paste("Figure3.2.7_2group_50run_case_1_99", "pdf",sep="."), width = 10, height=8)


### Pairwise difference between the performance of Limma and permutation 
differ.df<- df[df$test.name == "limma", c("group","cell.type","cp")]

differ.df$sensitivity.difference<- df[df$test.name == "permutation", "sensitivity"]-df[df$test.name == "limma", "sensitivity"]
differ.df$precision.difference<- df[df$test.name == "permutation", "precision"]-df[df$test.name == "limma", "precision"]
differ.df$F1.difference<- df[df$test.name == "permutation", "F1"]-df[df$test.name == "limma", "F1"]


differ.df$cp<- factor(differ.df$cp, levels=c("#Group1 : #Group2 \n = 5% : 95%",
                                             "#Group1 : #Group2 \n = 10% : 90%",
                                             "#Group1 : #Group2 \n = 20% : 80%",
                                             "#Group1 : #Group2 \n = 30% : 70%",
                                             "#Group1 : #Group2 \n = 40% : 60%",
                                             "#Group1 : #Group2 \n = 50% : 50%"))

sensitivity<-ggplot(data = differ.df, 
                    aes(x = factor(cell.type), y = sensitivity.difference, fill = factor(cell.type)))+
  geom_boxplot(size=0.2, width=0.8, position=position_dodge(1))+
  geom_point(size=0.3,position=position_jitterdodge(jitter.width=0.2, jitter.height=0))+
  facet_grid(~cp)+
  theme(legend.title=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="none",
        strip.text = element_text(size = rel(1)))+
  ylab("gained sensitivity")+  
  scale_y_continuous(limits=c(-0.5,0.5), oob = rescale_none)

precision<-ggplot(data = differ.df, 
                    aes(x = factor(cell.type), y =precision.difference, fill = factor(cell.type)))+
  geom_boxplot(size=0.2, width=0.8, position=position_dodge(1))+
  geom_point(size=0.3,position=position_jitterdodge(jitter.width=0.2, jitter.height=0))+
  facet_grid(~cp)+
  theme(legend.title=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=12), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="none",
        strip.text = element_text(size = rel(1)))+
  ylab("gained precision")+  
  scale_y_continuous(limits=c(-0.5,0.5), oob = rescale_none)
ggarrange(sensitivity, precision+xlab("moderated t statistic"),heights = c(3,3), 
          ncol = 1,  nrow = 2,
          legend="none", common.legend = T, align="hv")
ggsave(paste("Figure3.2.2_OT_pairwisediffernece", "pdf",sep="."), width = 12, height=5)

```
## Three Groups 
```{r}
groups_lst<- list(c(0.1, 0.1, 0.8),
                  c(0.2, 0.2, 0.6),
                  c(0.3, 0.3, 0.4))

# 1:20 runs -> 20run_3cp_g9897
# set.seed(22098)
# rep.times<-20
# rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
#                         size = length(groups_lst), replace = FALSE)

#set.seed(99899)
#rep.times<-30
#seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)
#rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+988, 
#                         size = length(groups_lst), replace = FALSE)
# rm(adj.p, adj.df)
      
set.seed(99899)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+988, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02, 0.02),
                         de.downProb = c(0, 0, 0),
                         group.prob = groups_lst[[cp]],
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1, 1.1),
                         de.facScale = c(0.5, 0.5, 0.5),
                         verbose = FALSE
                         )
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          Reduce(intersect, 
                                 list(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1],
                                      row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1],
                                      row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1])
                                 )
                          )
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    DE.g3<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1]
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0]), 
                      intersect(DE.g3, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g3<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
    }
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
  
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-8
    if (cp == 1){
      perm.size = 10000
    }else{
      perm.size = 4000
    }
   
    true.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    true.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    true.g3<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1]
    true.g1<- intersect(true.g1, row.names(sim))
    true.g2<- intersect(true.g2, row.names(sim))
    true.g3<- intersect(true.g3, row.names(sim))
    true.upreg = list(true.g1, true.g2, true.g3)
    
    perm.array.lst<- pPerm.stat(counts(sim), sim$Group, 
                                perm.size=perm.size, n.cores=n.cores)
    
    # generate perm & observation p-values for each stat 
    os.t.res<- runComparison.stat(sim, perm.size, statistic = "os.t", 
                                  sim_perm_arrays = perm.array.lst$os.t.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    os.modt.res<- runComparison.stat(sim, perm.size, statistic = "os.modt", 
                                  sim_perm_arrays = perm.array.lst$os.modt.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    lfc.p.res<-runComparison.stat(sim, perm.size, statistic = "lfc.p", 
                                  sim_perm_arrays = perm.array.lst$lfc.p.stat, 
                                  n.cores = n.cores, true.upreg = true.upreg)
    # save the result for each stat 
    saveRDS(os.t.res, paste(prefix, "os.t.Rds", sep=""))
    saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    saveRDS(os.modt.res, paste(prefix, "os.modt.Rds", sep="."))
    
    #os.t.res<- readRDS(paste(prefix, "os.t.Rds", sep=""))
   
    #lfc.p.res<- readRDS( paste(prefix, "lfc.p.Rds", sep="."))
    #os.modt.res<- readRDS(paste(prefix, "os.modt.Rds", sep="."))
    
    ############################################################################
    # creat the result table 
    stat.lst<- c("os.t","lfc.p", "os.modt")
    res.lst<- list(os.t.res, os.treatt.res,lfc.p.res, ts.modt.res,os.modt.res)
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      adj_50<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      auc.values <- computeAUC(result=res.lst[[a]], markers =res.lst[[a]]$true.upreg)
      
      adj.df<- computeComparison(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                                       marker.genes=res.lst[[a]]$true.upreg, 
                                    ids = paste(paste(as.character(table(sim$Group)),
                                                      collapse="_"), rep.seed[cp], sep="_"),
                             cell_num=as.vector(table(sim$Group)), 
                             perm.size=10000, auc.values=auc.values,
                             statistic=stat.lst[a])
  
      
    adj_50<- rbind(adj_50, adj.df)
    }
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)

adj_50<-readRDS("r50.3ct.adj.p.Rds")


adj_50[adj_50$TP==0, c("sensitivity","precision","F1")]=0
adj_50$category<- paste(adj_50$test.name, adj_50$statistic)
adj_50$category<- gsub(adj_50$category, pattern="os.t", replacement = "os.ordinary.t")
adj_50$category<- gsub(adj_50$category, pattern=".modt", replacement = ".moderated.t")
adj_50$category<- gsub(adj_50$category, pattern="lfc.p", replacement = "W")
gr<- unlist(groups_lst)*100

# combined=FALSE
cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 3, length(gr))),   
                                FUN= paste, collapse='%:'), 1))
adj_50$cp<- rep(paste("#Group1:#Group2:#Group3 = ",paste(cp.ft, "%",sep=""), sep=""),times=50,each = 30)
adj_50$cp<-factor(adj_50$cp, 
                 levels = c("#Group1:#Group2:#Group3 = 10%:10%:80%", 
                            "#Group1:#Group2:#Group3 = 20%:20%:60%",
                            "#Group1:#Group2:#Group3 = 30%:30%:40%")
                 )
df<- adj_50[adj_50$category %in% c("limma os.ordinary.t","permutation os.ordinary.t", 
                                           "limma os.moderated.t","permutation os.moderated.t", 
                                   "limma ts.moderated.t","permutation ts.moderated.t",
                                           "permutation W"), ]

df$category<- factor(df$category, levels=c("limma os.ordinary.t","permutation os.ordinary.t", 
                                           "limma os.moderated.t","permutation os.moderated.t", 
                                   "limma ts.moderated.t","permutation ts.moderated.t",
                                           "permutation W"))

clrs<- c('lightsteelblue2','navajowhite2', "steelblue2","darkgoldenrod1",
         "blue4","tomato3","green4")
sensitivity<-ggplot(data = df,
                    aes(x = factor(category), y = sensitivity,fill = factor(category)))+
  geom_boxplot(size=0.2, width=0.8)+
  geom_point(position=position_jitterdodge(jitter.width=0.4, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(axis.text.x = element_blank(), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=2, ncol =4))+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0.75,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)

precision<-ggplot(data = df,
                    aes(x = factor(category), y = precision,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.4, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(axis.text.x = element_blank(), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=2, ncol =4))+
  ylab("precision")+ 
  scale_y_continuous(limits=c(0.8,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)

f1<-ggplot(data = df,
           aes(x = factor(category), y = F1,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.4, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(legend.title=element_blank(),
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        axis.text.x = element_blank(),
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=18),
        strip.text = element_text(size = rel(1.1)))+
  guides(fill = guide_legend(nrow=2, ncol=4))+
  ylab("F1 score")+ 
  scale_y_continuous(limits=c(0.8,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)
ggarrange(sensitivity, precision, f1, ncol = 1,  nrow = 3,
          legend="bottom", common.legend = T,align="hv")
ggsave(paste("Figure3.3.1_3group_50run", "pdf",sep="."), width = 18, height=10)

```

### Efffect of number of Permutations 
```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
)

set.seed(23098)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)
cp=1
rep=1
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
set.seed(seed.number.cp[rep])
rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
                   size = length(groups_lst), replace = FALSE)
  sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                       batchCells = 1000, dropout.type = "none", out.prob = 0, 
                       de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                       group.prob = groups_lst[[1]],
                       seed = rep.seed[cp], 
                       de.facLoc = c(1.1, 1.1),
                       de.facScale = c(0.5, 0.5),
                       verbose = FALSE
  )
  


res_3k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=3000, 
                      statistic = "os.t",n.cores=10 )
res_5k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=5000, 
                      statistic = "os.t",n.cores=10)
res_10k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=10000, 
                      statistic = "os.t",n.cores=10)

res_30k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=30000, 
                      statistic = "os.t",n.cores=10 )
res_50k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=50000, 
                       statistic = "os.t",n.cores=10)
res_100k<-runPermuation(counts(sim), group=factor(sim$Group), perm.size=100000, 
                       statistic = "os.t",n.cores=10)


raw.p<- ggplot()+
  geom_boxplot(data=res_1k$result.table[[1]], aes(x = "1000 permutations", y =-log2(perm.raw.pvalue)))+
  geom_point(data=res_1k$result.table[[1]],position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2,aes(x = "1000 permutations", y = -log2(perm.raw.pvalue), fill=perm.raw.pvalue))+
  
  geom_boxplot(data=res_3k$result.table[[1]], aes(x = "3000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_3k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "3000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
  
  geom_boxplot(data=res_5k$result.table[[1]], aes(x = "5000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_5k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "5000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
  
  geom_boxplot(data=res_10k$result.table[[1]], aes(x = "10000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_10k$result.table[[1]],position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2,  aes(x = "10000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
  
  geom_boxplot(data=res_30k$result.table[[1]], aes(x = "30000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_30k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "30000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
   
  geom_boxplot(data=res_50k$result.table[[1]], aes(x = "50000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_50k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "50000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
 geom_boxplot(data=res_100k$result.table[[1]], aes(x = "100000 permutations", y = -log2(perm.raw.pvalue)))+
  geom_point(data=res_100k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             aes(x = "100000 permutations", y = -log2(perm.raw.pvalue),fill=perm.raw.pvalue))+
  ylab("-log2(raw p-value) for Group1")+
  scale_x_discrete(limits = c("1000 permutations","3000 permutations",
                                  "5000 permutations", "10000 permutations",
                                  "30000 permutations","50000 permutations",
                                  "100000 permutations"))+
  theme(legend.position = "none", axis.title.x = element_blank())+
  geom_hline(yintercept = 4.32, size=1, color="steelblue")+
  geom_text(aes(0,4.32,label = paste("-log2(0.05)"),hjust=0,  vjust = -0.5), size=4, color="black")+
  ylim(0, 8)


adj.p<- ggplot()+
  geom_boxplot(data=res_1k$result.table[[1]], aes(x = "1000 permutations", y =-log2(perm.adj.pvalue)))+
  geom_point(data=res_1k$result.table[[1]],position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2,aes(x = "1000 permutations", y = -log2(perm.adj.pvalue), fill=perm.adj.pvalue))+
  
  geom_boxplot(data=res_3k$result.table[[1]], aes(x = "3000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_3k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "3000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
  
  geom_boxplot(data=res_5k$result.table[[1]], aes(x = "5000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_5k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "5000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
  
  geom_boxplot(data=res_10k$result.table[[1]], aes(x = "10000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_10k$result.table[[1]],position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2,  aes(x = "10000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
  
  geom_boxplot(data=res_30k$result.table[[1]], aes(x = "30000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_30k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "30000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
   
  geom_boxplot(data=res_50k$result.table[[1]], aes(x = "50000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_50k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             size=0.2, aes(x = "50000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
  geom_boxplot(data=res_100k$result.table[[1]], aes(x = "100000 permutations", y = -log2(perm.adj.pvalue)))+
  geom_point(data=res_100k$result.table[[1]], position=position_jitterdodge(jitter.width=0.6, jitter.height=0), 
             aes(x = "100000 permutations", y = -log2(perm.adj.pvalue),fill=perm.adj.pvalue))+
  ylab("-log2(adjusted p-value) for Group1")+
  scale_x_discrete(limits = c("1000 permutations","3000 permutations",
                                  "5000 permutations", "10000 permutations",
                                  "30000 permutations","50000 permutations",
                                  "100000 permutations"))+
  theme(legend.position = "none",axis.title.x = element_blank())+#ylim(3, 8)+
  geom_hline(yintercept = 4.32, size=1, color="steelblue")+
  geom_text(aes(0,4.32,label = paste("-log2(0.05)"),hjust=0,  vjust = -0.5), size=4, color="black")+
  ylim(0, 8)

w<-ggarrange(raw.p, adj.p, ncol = 1,  nrow = 2,  legend="none",align="hv")

annotate_figure(w, top = text_grob("Distribution of Group1 p-vlaues with different number of permutations",
                                color = "black", face = "bold", size = 15))
ggsave(paste("Figure3.4.1_Num_permutations_pvalue", "pdf",sep="."), width = 10, height=7)

```