---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(splatter)
library(reshape2)
library(pROC)
library(ggforce) 
library(limma)
library(tictoc)
library(foreach)
library(scales)
library(ggplot2)
library(ggpubr)
library(ggExtra)
library(cowplot)

pbmc.data<- readRDS("pbmc_pooled_sex.Rds")
cm<- pbmc.data@assays$RNA@counts
table(pbmc.data$individual)

#subset_ind<- c("685_686", "689_690","691_692")
#cm<- pbmc.data[, pbmc.data$individual %in% subset_ind ]@assays$RNA@counts
cm<- pbmc.data[, pbmc.data$individual == "689_690"]@assays$RNA@counts
dim(cm) # 32738  3402 (1789+1613) $32738  4907

pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)


cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]
ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep


# with one cell type from one individual
selected_cells <- colnames(cm.processed[,pbmc.data[,colnames(cm.processed)]$predicted.celltype.l1 =="CD4 T"])
cm.processed.r<- cm.processed[, match(selected_cells, colnames(cm.processed))]
metadata <- data.frame(cell_type = pbmc.data[row.names(cm.processed.r),colnames(cm.processed.r)]$predicted.celltype.l1,
                       ind = '689_690')

#sce <- SingleCellExperiment(assays = as.matrix(cm.processed.r),
#                            colData=metadata)

sce <- SingleCellExperiment(list(counts=as.matrix(cm.processed.r)),colData=metadata)


curr_params <- newSplatParams()
# params <- setParam(params, "group.prob", ct_prop)
curr_params <- splatEstimate(sce,params = curr_params)


simulationQC<-function(sim, smaller.cp){
  # QC 
  # remove lowly expressed genes 
  numzero.genes <- rowSums(counts(sim)==0)
  keep.genes <- numzero.genes < (ncol(counts(sim))-min(smaller.cp*1000, 100))
  keep.genes <- setdiff(row.names(sim)[keep.genes],
                        intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                  row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
  sim<- sim[keep.genes, ]
  
  # check the logFC for each gene 
  obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
  DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
  DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
  
  neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                    intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
  )
  # remove true DEs with negative logFC
  if (length(neglogFC.DEs)>0) {
    sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
  }
  message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
  return(sim)
}
```

```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )

perm.size = 4000
set.seed(12202)
seed.number.cp <- sample(x = 100:10000, size = length(groups_lst), replace = FALSE)
rep<- 1

for (cp in 1:length(groups_lst)){
  print(cp)
  setwd("~/Desktop/Data Science Research Project/MDSresearchproject/different_cp_stat/global_seed_7654")
  sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                       batchCells = 1000, dropout.type = "none", out.prob = 0, 
                       de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                       group.prob = groups_lst[[cp]],
                       seed = seed.number.cp[cp], 
                       de.facLoc = c(1.1,1.1),
                       de.facScale = c(0.5, 0.5),
                       verbose = FALSE
                       )
  
  sim <- logNormCounts(sim)
  sim <- runPCA(sim)
  plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    theme(plot.title = element_text(size = 20, face = "bold"))
  
  
  numzero.genes <- rowSums(counts(sim)==0)
  keep.genes <- numzero.genes < (ncol(counts(sim))-groups_lst[[cp]][1]*1000)
  keep.genes <- setdiff(row.names(sim)[keep.genes],
                        intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                  row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
  sim<- sim[keep.genes, ]
  dim(sim)
  # check the logFC first
  obs_res<- computeObs(counts(sim), factor(sim$Group),statistic= "os.t")
  DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
  DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
  #summary(obs_res$summary.tb[DE.g1, "logFC.g1"])
  #summary(obs_res$summary.tb[DE.g2, "logFC.g2"])
  
  neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                    intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
  )
  # remove true DEs with negative logFC
  if (length(neglogFC.DEs)>0) {
    sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
    print(paste("processed dimension:", dim(sim)))
    #obs_res<- computeObs(counts(sim), factor(sim$Group),statistic= "os.t")
    #DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    #DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    #summary(obs_res$summary.tb[DE.g1, "logFC.g1"])
    #summary(obs_res$summary.tb[DE.g2, "logFC.g2"])
  }
  
  
  cp<-paste(as.character(table(sim$Group)),collapse="_")
  os.t.res<- runComparison(sim, perm.size, statistic = "os.t")
  os.treatt.res<- runComparison(sim, perm.size, statistic = "os.treatt")
  lfc.p.res<- runComparison(sim, perm.size, statistic = "lfc.p")
  saveRDS(os.t.res, paste(cp, "os.t.res.Rds", collapse="."))
  saveRDS(os.treatt.res, paste(cp, "os.treatt.Rds", collapse="."))
  saveRDS(lfc.p.res, paste(cp, "lfc.p.Rds", collapse="."))
  #os.t.res<-readRDS(paste(cp, "os.t.res.Rds", collapse="."))
  #os.treatt.res<-readRDS(paste(cp, "os.treatt.Rds", collapse="."))
  #lfc.p.res<-readRDS(paste(cp, "lfc.p.Rds", collapse="."))
  stat.lst<- c("os.t","os.treatt", "lfc.p")
  res.lst<- list(os.t.res, os.treatt.res,lfc.p.res)

  if (exists("adj.df") == FALSE ){
    cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
              "TP", "precision", "sensitivity","overlap","TP.overlap","cutoff","perm.size",
              "seed.number","AUC","statistic")
    raw.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)), cols.n)
    adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
  }
  for (a in 1:length(stat.lst)){
    auc.values <- plotComparison(sim, perm.size = perm.size, seed.n = seed.number.cp[cp], 
                                 result=res.lst[[a]])
    raw.df<-computeSummary3(res.lst[[a]]$obs.pval, res.lst[[a]]$perm.pval,
                            adj = "",
                            true.upreg = res.lst[[a]]$true.upreg, 
                            cell_num = as.vector(table(sim$Group)), 
                            main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                            seed.number=seed.number.cp[cp],perm.size=perm.size, 
                            auc.values=auc.values, statistic = stat.lst[[a]])
    
    adj.df<-computeSummary3(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                            adj = "adjusted",
                            true.upreg = res.lst[[a]]$true.upreg, 
                            cell_num=as.vector(table(sim$Group)), 
                            main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                            seed.number=seed.number.cp[cp],perm.size=perm.size,
                            auc.values=auc.values, statistic = stat.lst[[a]])
    raw.p<- rbind(raw.p, raw.df)
    adj.p<- rbind(adj.p, adj.df)
  }
  
}
saveRDS(raw.p, "raw.p.Rds")
saveRDS(adj.p, "adj.p.Rds")
```

```{r}
adj.p<-readRDS("~/Desktop/Data Science Research Project/MDSresearchproject/different_cp_stat/global_seed_12202/adj.p.Rds")
colnames(adj.p)
adj.p$group<- factor(adj.p$group)
adj.p[adj.p$statistic=="lfc.p"&adj.p$test.name=="limma","statistic"]<-"os.t"
adj.p[adj.p$TP==0,"precision"]<-0


adj.p$group <- factor(adj.p$group,levels = as.vector(unique(adj.p$group)))

adj.p$category <- paste(adj.p$test.name, adj.p$statistic)
adj.p$category<-factor(adj.p$category, levels = c("limma os.t", 
                                                  "permutation os.t",
                                                  "limma os.treatt",
                                                  "permutation os.treatt", "permutation lfc.p"))

sensitivity.chart<-ggplot(data = adj.p, 
                          aes(x = group, y = sensitivity,fill = category))+
  geom_bar(width=0.65, stat="identity",color="black", position=position_dodge())+
  facet_wrap(~cell.type, nrow=2)+
  theme(axis.text.x = element_text(angle=90), legend.title=element_blank())+
  xlab("")+ylab("sensitivity")+ scale_y_continuous(limits=c(0.4, 1),oob = rescale_none)+scale_fill_manual(values=c('cyan','coral',"cyan3","darkgoldenrod1","brown2"))  #+scale_fill_brewer(palette="Set1")


precision.chart<-ggplot(data = adj.p, 
                        aes(x = group, y = precision,fill = category))+
  geom_bar(width=0.65, stat="identity",color="black", position=position_dodge())+
  facet_wrap(~cell.type, nrow=2)+
  theme(axis.text.x = element_text(angle=90), legend.title=element_blank())+
  xlab("")+ylab("precision")+ scale_y_continuous(limits=c(0.7, 1),oob = rescale_none)+
  scale_fill_manual(values=c('cyan','coral',"cyan3","darkgoldenrod1","brown2")) 
  #scale_fill_brewer(palette="Set1")
#+scale_fill_manual(values=c('#00BA42','orange',"pink")) #+ggtitle("adjusted pvalues")#
#ggsave("simulation_result_num_upreg_adj.pdf", width = 8, height=6)

numcells.barchart<- ggplot(data = adj.p, 
                           aes(x = group, y = num.cells, fill =cell.type))+
  scale_y_continuous(position = "right")+
  geom_bar(stat="identity", position=position_dodge())+
  theme(axis.text.x = element_text(angle=90), legend.title=element_blank())+
  xlab("")+ylab("number of cells")+
  geom_text(aes(label=num.cells), vjust=1.6, color="black",
            position = position_dodge(0.9), size=3.5)

numcells.barchart<- ggplot(data = adj.p, 
                           aes(x = group, y = num.cells))+
  scale_y_continuous(position = "right")+
  geom_bar(stat="identity", fill="cornsilk3",position=position_dodge())+facet_wrap(~cell.type, nrow=2)+
  theme(axis.text.x = element_text(angle=90), 
        axis.text.y = element_blank(),legend.title=element_blank(), 
        axis.ticks = element_line(size = 0), 
        panel.grid=element_line(size = 0),
        panel.background = element_rect(fill = "white"))+
  xlab("")+ylab("number of cells")+
  geom_text(aes(label=num.cells), vjust=0, color="black",
            position = position_dodge(0.9), size=2)


line.chart<- ggplot(data = adj.p, aes(x = group, y = sensitivity,colour = statistic,
                                      group =statistic))+
  geom_line()+
  #geom_bar(aes(x=group, y=num.cells/1000),stat="identity", color="black", position=position_dodge())+
  geom_point(aes(color = statistic))+
  facet_grid(cell.type~test.name)+#ggtitle("adjusted pvalues")+
  theme(axis.text.x = element_text(angle=90), legend.title=element_blank())+
  xlab("")+ylab("sensitivity")

ggarrange(precision.chart, sensitivity.chart, heights = c(3,3), ncol = 2,  nrow = 1,
          widths=c(2, 2),legend="top", common.legend = T)

ggarrange(precision.chart, numcells.barchart, heights = c(3,3), ncol = 2,  nrow = 1,
          widths=c(5, 2),legend="top", common.legend = T)
ggsave("barchart_simulation_result_pres.pdf", width = 8, height=6)
```
repeted version II of the second code chunk
calculate different stat at one single perm run 
```{r}

groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )

# 1:20 runs -> 20run_7cp_g22098
# set.seed(22098)
# rep.times<-20
# rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+8900, 
#                         size = length(groups_lst), replace = FALSE)
# 20:50 runs -> 30run_7cp_g23098
#set.seed(23098)
#rep.times<-30
#rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
#                         size = length(groups_lst), replace = FALSE)
set.seed(23098)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

# rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    
    #sim <- logNormCounts(sim)
    #sim <- runPCA(sim)
    #plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    #  theme(plot.title = element_text(size = 20, face = "bold"))
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    #summary(obs_res$summary.tb[DE.g1, "logFC.g1"])
    #summary(obs_res$summary.tb[DE.g2, "logFC.g2"])
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
    }
   # sim<-simulationQC(sim, groups_lst[[cp]][1])
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-8
    if (cp == 1){
      perm.size = 10000
    }else{
      perm.size = 4000
    }
    #perm.array.lst<- pPerm.stat(counts(sim), sim$Group, 
    #                            perm.size=perm.size, n.cores=n.cores)
    #true.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    #true.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    #true.g1<- intersect(true.g1, row.names(sim))
    #true.g2<- intersect(true.g2, row.names(sim))
    #true.upreg = list(true.g1, true.g2)
    # generate perm & observation p-values for each stat 
    #os.t.res<- runComparison.stat(sim, perm.size, statistic = "os.t", 
    #                              sim_perm_arrays = perm.array.lst$os.t.stat, 
    #                              n.cores = n.cores,true.upreg=true.upreg)
    #os.modt.res<- runComparison.stat(sim, perm.size, statistic = "os.modt", 
    #                              sim_perm_arrays = perm.array.lst$os.modt.stat, 
    #                              n.cores = n.cores,true.upreg=true.upreg)
    #os.treatt.res<- runComparison.stat(sim, perm.size, statistic = "os.treatt", 
    #                              sim_perm_arrays = perm.array.lst$os.treatt.stat, 
    #                              n.cores = n.cores,true.upreg=true.upreg)
    #ts.modt.res<- runComparison.stat(sim, perm.size, statistic = "ts.modt", 
    #                              sim_perm_arrays = perm.array.lst$ts.modt.stat,
    #                              n.cores = n.cores,true.upreg=true.upreg)
    #lfc.p.res<-runComparison.stat(sim, perm.size, statistic = "lfc.p", 
    #                              sim_perm_arrays = perm.array.lst$lfc.p.stat, 
    #                              n.cores = n.cores,true.upreg=true.upreg)
    # save the result for each stat 
    #saveRDS(os.t.res, paste(prefix, "os.t.Rds", sep="."))
    #saveRDS(os.treatt.res, paste(prefix, "os.treatt.Rds", sep="."))
    #saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    #saveRDS(ts.modt.res, paste(prefix, "ts.modt.Rds", sep="."))
    #saveRDS(os.modt.res, paste(prefix, "os.modt.Rds", sep="."))
    #setwd("~/Desktop/Data Science Research Project/MDSresearchproject/50run_7cp/30run_7cp_g23098")
    setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_7cp/30run_7cp_g23098")
    os.t.res<- readRDS(paste(prefix, "os.t.Rds", sep="."))
    os.treatt.res<- readRDS(paste(prefix, "os.treatt.Rds", sep="."))
    lfc.p.res<- readRDS( paste(prefix, "lfc.p.Rds", sep="."))
    ts.modt.res<- readRDS(paste(prefix, "ts.modt.Rds", sep="."))
    os.modt.res<- readRDS(paste(prefix, "os.modt.Rds", sep="."))
    
    ############################################################################
    # creat the result table 
    stat.lst<- c("os.t","os.treatt", "lfc.p","ts.modt", "os.modt")
    res.lst<- list(os.t.res, os.treatt.res,lfc.p.res, ts.modt.res,os.modt.res)
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      auc.values <- plotComparison(sim, perm.size = perm.size,
                                   plt.main = paste(prefix,stat.lst[a],"pdf", sep="."), 
                                   result=res.lst[[a]])
      if (stat.lst[a] == "ts.modt" | stat.lst[a] == "os.treatt"){
        logFC.df<- as.data.frame(cbind(res.lst[[a]]$result.table[[1]][, 2],
                                             res.lst[[a]]$result.table[[2]][, 2]))
        row.names(logFC.df)<-row.names(res.lst[[a]]$obs.stat)
        colnames(logFC.df)<-c("logFC.g1","logFC.g2")
      trueDE<-res.lst[[a]]$true.upreg
        if(stat.lst[a] == "os.treatt"){
          trueDE = list(intersect(row.names(logFC.df[logFC.df$logFC.g1 > 0.1, ]),
                                  trueDE[[1]]), 
                        intersect(row.names(logFC.df[logFC.df$logFC.g2 > 0.1, ]),
                                  trueDE[[2]]))
        }
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = trueDE, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              logFC.df=logFC.df,
                              auc.values=auc.values, statistic = stat.lst[[a]], 
                              combined=TRUE)
      }else{
      
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = res.lst[[a]]$true.upreg, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              auc.values=auc.values, statistic = stat.lst[[a]],
                              combined=TRUE)
      
      }
      
      
     #z<- rbind(z, adj.df)
    adj.p<- rbind(adj.p, adj.df)
    }
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)
saveRDS(adj.p, "r50.combined.adj.p.Rds")
```

three groups
```{r}
groups_lst<- list(c(0.1, 0.1, 0.8),
                  c(0.2, 0.2, 0.6),
                  c(0.3, 0.3, 0.4)
                  )

# 1:20 runs -> 20run_3cp_g9897
# set.seed(22098)
# rep.times<-20
# rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
#                         size = length(groups_lst), replace = FALSE)

#set.seed(99899)
#rep.times<-30
#seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)
#rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+988, 
#                         size = length(groups_lst), replace = FALSE)
# rm(adj.p, adj.df)
      
set.seed(99899)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+988, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02, 0.02),
                         de.downProb = c(0, 0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1, 1.1),
                         de.facScale = c(0.5, 0.5, 0.5),
                         verbose = FALSE
                         )
    
    #sim <- logNormCounts(sim)
    #sim <- runPCA(sim)
    #plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    #  theme(plot.title = element_text(size = 20, face = "bold"))
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          Reduce(intersect, 
                                 list(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1],
                                      row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1],
                                      row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1])
                                 )
                          )
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    DE.g3<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1]
    #summary(obs_res$summary.tb[DE.g1, "logFC.g1"])
    #summary(obs_res$summary.tb[DE.g2, "logFC.g2"])
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0]), 
                      intersect(DE.g3, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g3<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
    }
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
   # setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_3cp/20run_3cp_g9897")
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    prefix<-paste("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_3cp/30run_3cp_g99899/", 
                  prefix, sep="")
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-8
    if (cp == 1){
      perm.size = 10000
    }else{
      perm.size = 4000
    }
    perm.array.lst<- pPerm.stat(counts(sim), sim$Group, 
                                perm.size=perm.size, n.cores=n.cores)
    
    true.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    true.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    true.g3<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup3 > 1]
    true.g1<- intersect(true.g1, row.names(sim))
    true.g2<- intersect(true.g2, row.names(sim))
    true.g3<- intersect(true.g3, row.names(sim))
    true.upreg = list(true.g1, true.g2, true.g3)
    
    
    # generate perm & observation p-values for each stat 
    os.t.res<- runComparison.stat(sim, perm.size, statistic = "os.t", 
                                  sim_perm_arrays = perm.array.lst$os.t.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    os.modt.res<- runComparison.stat(sim, perm.size, statistic = "os.modt", 
                                  sim_perm_arrays = perm.array.lst$os.modt.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    os.treatt.res<- runComparison.stat(sim, perm.size, statistic = "os.treatt", 
                                  sim_perm_arrays = perm.array.lst$os.treatt.stat, 
                                  n.cores = n.cores,true.upreg = true.upreg)
    ts.modt.res<- runComparison.stat(sim, perm.size, statistic = "ts.modt", 
                                  sim_perm_arrays = perm.array.lst$ts.modt.stat,
                                  n.cores = n.cores,true.upreg = true.upreg)
    lfc.p.res<-runComparison.stat(sim, perm.size, statistic = "lfc.p", 
                                  sim_perm_arrays = perm.array.lst$lfc.p.stat, 
                                  n.cores = n.cores, true.upreg = true.upreg)
    # save the result for each stat 
    #setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_7cp/10run_3cp_g9897/")
    saveRDS(os.t.res, paste(prefix, "os.t.Rds", sep=""))
    saveRDS(os.treatt.res, paste(prefix, "os.treatt.Rds", sep="."))
    saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    saveRDS(ts.modt.res, paste(prefix, "ts.modt.Rds", sep="."))
    saveRDS(os.modt.res, paste(prefix, "os.modt.Rds", sep="."))
    
    #os.t.res<- readRDS(paste(prefix, "os.t.Rds", sep=""))
    #os.treatt.res<- readRDS(paste(prefix, "os.treatt.Rds", sep="."))
    #lfc.p.res<- readRDS( paste(prefix, "lfc.p.Rds", sep="."))
    #ts.modt.res<- readRDS(paste(prefix, "ts.modt.Rds", sep="."))
    #os.modt.res<- readRDS(paste(prefix, "os.modt.Rds", sep="."))
    
    ############################################################################
    # creat the result table 
    stat.lst<- c("os.t","os.treatt", "lfc.p","ts.modt", "os.modt")
    res.lst<- list(os.t.res, os.treatt.res,lfc.p.res, ts.modt.res,os.modt.res)
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      auc.values <- plotComparison(sim, perm.size = perm.size,
                                   plt.main = paste(prefix,stat.lst[a],"pdf", sep="."), 
                                   result=res.lst[[a]], groups=3)
      if (stat.lst[a] == "ts.modt" | stat.lst[a] == "os.treatt"){
        logFC.df<- as.data.frame(cbind(res.lst[[a]]$result.table[[1]][, 1],
                                       res.lst[[a]]$result.table[[2]][, 1],
                                       res.lst[[a]]$result.table[[3]][, 1])
                                 )
        row.names(logFC.df)<-row.names(res.lst[[a]]$obs.stat)
        colnames(logFC.df)<-c("logFC.g1","logFC.g2","logFC.g3")
      trueDE<-true.upreg
        if(stat.lst[a] == "os.treatt"){
          trueDE = list(intersect(row.names(logFC.df[logFC.df$logFC.g1 > 0.1, ]),
                                  true.upreg[[1]]), 
                        intersect(row.names(logFC.df[logFC.df$logFC.g2 > 0.1, ]),
                                  true.upreg[[2]]),
                         intersect(row.names(logFC.df[logFC.df$logFC.g3 > 0.1, ]),
                                  true.upreg[[3]]))
        }
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = trueDE, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              logFC.df=logFC.df,
                              auc.values=auc.values, statistic = stat.lst[[a]], 
                              combined=FALSE)
      }else{
      
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = res.lst[[a]]$true.upreg, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              auc.values=auc.values, statistic = stat.lst[[a]],
                              combined=FALSE)
      
      }
     #z<- rbind(z, adj.df)
    adj.p<- rbind(adj.p, adj.df)
    }
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)
setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_3cp/20run_3cp_g9897/")
adj_20<-readRDS("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_3cp/20run_3cp_g9897/r20.3ct.adj.p.Rds")
#saveRDS(adj_50, "r50.3ct.adj.p.Rds")
adj_50<- rbind(adj_20, adj.p)
```


```{r}
adj.p<- readRDS("/Users/MelodyJin/Desktop/Data Science Research Project/MDSresearchproject/50run_7cp/V2_50r_adj.p.Rds")
adj.p$group<- factor(adj.p$group)
adj.p[adj.p$statistic=="lfc.p"&adj.p$test.name=="limma","statistic"]<-"os.t"

adj.p[adj.p$TP==0,"precision"]<-0
adj.p[adj.p$TP==0,"sensitivity"]<-0
adj.p[adj.p$TP==0,"F1"]<-0

adj.p$group <- factor(adj.p$group,levels = as.vector(unique(adj.p$group)))

adj.p$category <- paste(adj.p$test.name, adj.p$statistic)
adj.p$category<-factor(adj.p$category, levels = c("limma os.t", 
                                                  "permutation os.t",
                                                  "limma os.treatt",
                                                  "permutation os.treatt",
                                                  "limma os.modt", 
                                                  "permutation os.modt",
                                                  "limma ts.modt", 
                                                  "permutation ts.modt",
                                                  "permutation lfc.p"))
gr<- unlist(groups_lst)*100

# combined=FALSE, group=3
cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 3, length(gr))),   
                                FUN= paste, collapse=':'), 1))
adj.p$cp<- rep(paste("group1:group2:group3 = ",cp.ft, sep=""),times=30,each = 6*5)
adj.p$cp<-factor(adj.p$cp, levels = c("group1:group2:group3 = 10:10:80",
                                      "group1:group2:group3 = 20:20:60",
                                      "group1:group2:group3 = 30:30:40")
                 )

# combined=FALSE
cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 2, length(gr))),   
                                FUN= paste, collapse='% : '), 1))
adj.p$cp<- rep(paste("#group1 : #group2 = ",paste(cp.ft, "%",sep=""), sep=""),times=5,each = 10)
adj.p$cp<-factor(adj.p$cp, 
                 levels = c("#group1 : #group2 = 1% : 99%",
                            "#group1 : #group2 = 5% : 95%",
                            "#group1 : #group2 = 10% : 90%",
                            "#group1 : #group2 = 20% : 80%",
                            "#group1 : #group2 = 30% : 70%",
                            "#group1 : #group2 = 40% : 60%",
                            "#group1 : #group2 = 50% : 50%")
                 )
# combined = TRUE
adj.p$cp<- rep(cp.ft,times=5,each = 2*5)

adj.p$cp<-factor(adj.p$cp, levels = c("1_99","5_95","10_90","20_80","30_70","40_60","50_50"))
cps<-c("#group1 : #group2 = 1% : 99%",
       "#group1 : #group2 = 5% : 95%",
       "#group1 : #group2 = 10% : 90%",
       "#group1 : #group2 = 20% : 80%",
       "#group1 : #group2 = 30% : 70%",
       "#group1 : #group2 = 40% : 60%",
       "#group1 : #group2 = 50% : 50%")
ntstat_lst<-c("limma os.t", 
                "permutation os.t",
                "limma os.modt", 
                "permutation os.modt",
                "limma ts.modt", 
                "permutation ts.modt",
                "permutation lfc.p")

adj.p.tt<- adj.p[adj.p$category%in% c("limma os.treatt", "permutation os.treatt"), ]

adj.p.osts<- adj.p[adj.p$category %in% ntstat_lst[c(1,2,5,6)], ]
adj.p.ost<- adj.p[adj.p$category %in% ntstat_lst[c(1,2,3,4, 7)], ]

adj.p.less<-adj.p[adj.p$cp %in% c(#"#group1 : #group2 = 5% : 95%",
                            "#group1 : #group2 = 10% : 90%",
                            "#group1 : #group2 = 20% : 80%",
                            "#group1 : #group2 = 30% : 70%",
                            "#group1 : #group2 = 40% : 60%",
                            "#group1 : #group2 = 50% : 50%"), ]


plot.result<-function(df, name, clrs, prec.ylim=c(0, 1), sens.ylim=c(0,1),
                      f1.ylim=c(0,1), selected_cps){
  if (length(selected_cps)>0){
    df<-df[which(df$cp %in% selected_cps), ]
  }
  sensitivity<-ggplot(data = df, 
                      aes(x = factor(category), y = sensitivity,fill = category))+
    geom_boxplot(size=0.2, width= 0.5, position=position_dodge(1))+
    geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
               size=0.4, color = "black", alpha=0.9)+
    facet_grid(cell.type~cp, scales='free_x', space='free_x')+
    theme(axis.text.x = element_text(angle=90), 
          legend.title=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.text.x.bottom =element_blank(), 
          axis.title.x=element_blank(),
          axis.title.y=element_text(size=20), 
          panel.spacing = unit(0.5, "lines"), 
          legend.position="top", #legend.text=element_text(),
          #legend.spacing.x = unit(0.6, 'cm'),
          legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=14),
          strip.text = element_text(size = rel(1.5)))+
    guides(fill = guide_legend(ncol =length(clrs)))+
    #xlab("")+
    ylab("sensitivity")+ 
    scale_y_continuous(limits=sens.ylim, oob = rescale_none)+
    scale_fill_manual(values=clrs)
  precision<-ggplot(data = df, 
                    aes(x = factor(category), y = precision,fill = category))+
    geom_boxplot(size=0.2,  width= 0.5, position=position_dodge(1))+
    geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
               size=0.4, color = "black", alpha=0.9)+
    facet_grid(cell.type~cp, scales='free_x', space='free_x')+
    theme(axis.text.x = element_text(angle=90), 
          legend.title=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.text.x.bottom =element_blank(), 
          axis.title.x=element_blank(),
          axis.title.y=element_text(size=20), 
          panel.spacing = unit(0.5, "lines"), 
          legend.position="top", 
          legend.text=element_text(margin=margin(r=0.3,unit="cm"),size=14),
          strip.text = element_text(size = rel(1.5)))+
    guides(fill = guide_legend(ncol = length(clrs)))+
    #xlab("")+
    ylab("precision")+ 
    scale_y_continuous(limits=prec.ylim, oob = rescale_none)+
    scale_fill_manual(values=clrs)
  f1<-ggplot(data = df, 
             aes(x = factor(category), y = F1,fill = category))+
    geom_boxplot(size=0.2, position=position_dodge(1))+
    geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
               size=0.4, color = "black", alpha=0.9)+
    facet_grid(cell.type~cp, scales='free_x', space='free_x')+
    theme(axis.text.x = element_text(angle=90), 
          legend.title=element_blank(),
          axis.ticks.x=element_blank(), 
          axis.text.x.bottom =element_blank(), 
          axis.title.x=element_blank(),
          panel.spacing = unit(0.5, "lines"), 
          legend.position="top", 
          legend.text=element_text(margin=margin(r=0.5,unit="cm"),size=10), 
          strip.text = element_text(size = rel(2)))+
    guides(fill = guide_legend(ncol = length(clrs)))+
    #xlab("")+
    ylab("F1 score")+ 
    scale_y_continuous(limits=f1.ylim, oob = rescale_none)+
    scale_fill_manual(values=clrs)
  ggarrange(precision, sensitivity, heights = c(3,3), ncol = 1,  nrow = 2,
            legend="top", common.legend = T,align="hv")
  ggsave(paste(name, "pdf",sep="."), width = 10, height=8)
  return (list(precision, sensitivity, f1))
  
}

plot.result(df=adj.p, name="www",  clrs = c('lightsteelblue2','navajowhite2',
                 "steelblue2","darkgoldenrod1",
                 "royalblue1","coral","blue4","tomato3",
                 "green4"),selected_cps =cps)
ggarrange(sensitivity.small, sensitivity.larger, heights = c(1,1), ncol = 2,  nrow = 1,
            legend="top", common.legend = T)
 
plot.result(df=adj.p.tt, name="adj.p.r50.7ct.tt.cp12", clrs = c("steelblue2","darkgoldenrod1"), 
            selected_cps =cps[c(1,2)], c(0, 1), c(0, 1),c(0.8, 1))

plot.result(df=adj.p.osts, name="adj.p.r50.7ct.osts", clrs = c('lightsteelblue2','navajowhite2',"blue4","tomato3"))
plot.result(df=adj.p.ost, name="adj.p.r50.7ct.ost", clrs = c('lightsteelblue2','navajowhite2',
                 "royalblue1","coral","green4"))

plot.result(df=adj.p.ost, name="adj.p.r50.7ct.ost.cp12", 
            clrs = c('lightsteelblue2','navajowhite2',
                 "royalblue1","coral","green4"), 
            selected_cps =cps[c(1,2)], c(0, 1), c(0, 1),c(0.8, 1)
            )

```
 vary DE proportion
```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )
set.seed(9867)
rep.times<-5
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

# rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+98, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.1, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    
    #sim <- logNormCounts(sim)
    #sim <- runPCA(sim)
    #plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    #  theme(plot.title = element_text(size = 20, face = "bold"))
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
      obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
      DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
      DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    }
    
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    print("Group1 true DE logFC summary")
    print(summary(obs_res$summary.tb[DE.g1, "logFC.g1"]))
    print("Group2 true DE logFC summary")
    print(summary(obs_res$summary.tb[DE.g2, "logFC.g2"]))
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-8
    if (cp == 1){
      perm.size = 10000
    }else{
      perm.size = 4000
    }
    #perm.array.lst<- pPerm.stat(counts(sim), sim$Group, 
    #                            perm.size=perm.size, n.cores=n.cores)
    
    # generate perm & observation p-values for each stat 
    #os.t.res<- runComparison.stat(sim, perm.size, statistic = "os.t", 
    #                              sim_perm_arrays = perm.array.lst$os.t.stat, 
    #                              n.cores = n.cores)
    #os.modt.res<- runComparison.stat(sim, perm.size, statistic = "os.modt", 
    #                              sim_perm_arrays = perm.array.lst$os.modt.stat, 
    #                              n.cores = n.cores)
    #os.treatt.res<- runComparison.stat(sim, perm.size, statistic = "os.treatt", 
    #                              sim_perm_arrays = perm.array.lst$os.treatt.stat, 
    #                              n.cores = n.cores)
    #ts.modt.res<- runComparison.stat(sim, perm.size, statistic = "ts.modt", 
    #                             sim_perm_arrays = perm.array.lst$ts.modt.stat,
    #                              n.cores = n.cores)
    #lfc.p.res<-runComparison.stat(sim, perm.size, statistic = "lfc.p", 
    #                              sim_perm_arrays = perm.array.lst$lfc.p.stat, 
    #                              n.cores = n.cores)
    # save the result for each stat 
    #saveRDS(os.t.res, paste(prefix, "os.t.Rds", sep="."))
    #saveRDS(os.treatt.res, paste(prefix, "os.treatt.Rds", sep="."))
    #saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    #saveRDS(ts.modt.res, paste(prefix, "ts.modt.Rds", sep="."))
    #saveRDS(os.modt.res, paste(prefix, "os.modt.Rds", sep="."))
    setwd("~/Desktop/Data Science Research Project/MDSresearchproject/5run_differDEprop")
    os.t.res<- readRDS(paste(prefix, "os.t.Rds", sep="."))
    os.treatt.res<- readRDS(paste(prefix, "os.treatt.Rds", sep="."))
    lfc.p.res<- readRDS( paste(prefix, "lfc.p.Rds", sep="."))
    ts.modt.res<- readRDS(paste(prefix, "ts.modt.Rds", sep="."))
    os.modt.res<- readRDS(paste(prefix, "os.modt.Rds", sep="."))
    
    ############################################################################
    # creat the result table 
    stat.lst<- c("os.t","os.treatt", "lfc.p","ts.modt", "os.modt")
    res.lst<- list(os.t.res, os.treatt.res,lfc.p.res, ts.modt.res,os.modt.res)
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      auc.values <- plotComparison(sim, perm.size = perm.size,
                                   plt.main = paste(prefix,stat.lst[a],"pdf", sep="."), 
                                   result=res.lst[[a]])
      if (stat.lst[a] == "ts.modt" | stat.lst[a] == "os.treatt"){
        logFC.df<- as.data.frame(cbind(res.lst[[a]]$result.table[[1]][, 2],
                                             res.lst[[a]]$result.table[[2]][, 2]))
        row.names(logFC.df)<-row.names(res.lst[[a]]$obs.stat)
        colnames(logFC.df)<-c("logFC.g1","logFC.g2")
      trueDE<-res.lst[[a]]$true.upreg
        if(stat.lst[a] == "os.treatt"){
          trueDE = list(intersect(row.names(logFC.df[logFC.df$logFC.g1 > 0.01, ]),
                                  trueDE[[1]]), 
                        intersect(row.names(logFC.df[logFC.df$logFC.g2 > 0.01, ]),
                                  trueDE[[2]]))
        }
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = trueDE, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              logFC.df=logFC.df,
                              auc.values=auc.values, statistic = stat.lst[[a]], 
                              combined=FALSE)
      }else{
      
      adj.df<-computeSummary3simple(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = res.lst[[a]]$true.upreg, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              auc.values=auc.values, statistic = stat.lst[[a]],
                              combined=FALSE)
      
      }
      
      
     #z<- rbind(z, adj.df)
    adj.p<- rbind(adj.p, adj.df)
    }
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)

```

try different logFC for treat t statistic
DE logFC summary  
```{r}
logFC.g1<-matrix(nrow=7, ncol=15)
colnames(logFC.g1)<-c("cp","trueDE","DEt0.05","DE0.1","DEt0.2","DEt0.4","DEt0.6","DEt0.8","DEt1",
                      "Min.", "1st Qu.","Median","Mean", "3rd Qu.", "Max." )
logFC.g2<-matrix(nrow=7, ncol=15) 
colnames(logFC.g2)<-c("cp","trueDE","DEt0.05","DE0.1","DEt0.2","DEt0.4","DEt0.6","DEt0.8","DEt1",
                      "Min.", "1st Qu.","Median","Mean", "3rd Qu.", "Max." )

for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    # QC 
    sim<-simulationQC(sim, groups_lst[[cp]][1])
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")

    #
    setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_7cp/30run_7cp_g23098")
    os.treatt.res<- readRDS(paste(prefix, "os.treatt.Rds", sep="."))

    logFC.df<- as.data.frame(cbind(os.treatt.res$result.table[[1]][, 2],
                                   os.treatt.res$result.table[[2]][, 2]))
    colnames(logFC.df)<-c("logFC.g1", "logFC.g2")
    row.names(logFC.df)<-row.names(os.treatt.res$obs.stat)
    #print("group1 true DE summary")
    logFC.g1[cp, 1]<-paste(groups_lst[[cp]]*100,collapse="_")
    logFC.g2[cp, 1]<-paste(groups_lst[[cp]]*100,collapse="_")
    
    logFC.vals<- c(0.05, 0.1, 0.2, 0.4, 0.6, 0.8, 1)
    trueDE<-os.treatt.res$true.upreg
    logFC.g1[cp, 2]<-length(trueDE[[1]])
    logFC.g2[cp, 2]<-length(trueDE[[2]])
    for (i in 1:length(logFC.vals)){
      logFC.g1[cp, i+2]<-length(intersect(row.names(logFC.df[logFC.df$logFC.g1 > logFC.vals[i], ]),
                                          trueDE[[1]]))
      logFC.g2[cp, i+2]<-length(intersect(row.names(logFC.df[logFC.df$logFC.g2 > logFC.vals[i], ]),
                                          trueDE[[2]]))
    }
    logFC.g1[cp,10:15]<- round(as.vector(summary(logFC.df[os.treatt.res$true.upreg[[1]], "logFC.g1"])), 5)
    #print("group1 true DE summary")
    logFC.g2[cp,10:15]<-round(as.vector(summary(logFC.df[os.treatt.res$true.upreg[[2]], "logFC.g2"])), 5)
}

```

same code as vary DE, try to get more ideas about true DE distribution 
```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5),
                  c(0.6, 0.4),
                  c(0.7, 0.3),
                  c(0.8, 0.2),
                  c(0.9, 0.1), 
                  c(0.95, 0.05), 
                  c(0.99, 0.01)
                  )
set.seed(9867)
rep.times<-5
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

# rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
logFC.lst<-list()
for (rep in 1: 1){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+98, 
                     size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.1, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
    )
    
    #sim <- logNormCounts(sim)
    #sim <- runPCA(sim)
    #plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    #  theme(plot.title = element_text(size = 20, face = "bold"))
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
      obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
      DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
      DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    }
    
    dt<-limma::decideTests(obs_res$fit.cont.eb.obs)
    tp.g1<- row.names(obs_res$fit.cont.eb.obs) %in% DE.g1
    tp.g2<- row.names(obs_res$fit.cont.eb.obs) %in% DE.g2
    pdf(paste("seed",rep.seed[cp], paste(as.character(groups_lst[[cp]]*100), 
                                  collapse = "vs"),"MAplot","pdf",sep="."))
    limma::plotMA(obs_res$fit.cont.eb.obs, coef=1, status =tp.g1, main = "Group1 true DE", 
                  legend = "bottomright")
    limma::plotMA(obs_res$fit.cont.eb.obs, coef=2, status =tp.g2, main = "Group2 true DE",
                  legend = "bottomright")
    dtt<- matrix("TN", nrow=nrow(obs_res$fit.cont.eb.obs), ncol=2)
    dtt<-as.data.frame(dtt)
    row.names(dtt)<-row.names(obs_res$fit.cont.eb.obs)
    colnames(dtt)<-c("group1","group2")
    
    dtt[intersect(row.names(dt)[dt[,1]==-1], setdiff(row.names(dtt),DE.g1)),1]<-"TN"
    dtt[intersect(row.names(dt)[dt[,1]==0] , setdiff(row.names(dtt),DE.g1)),1]<-"TN"
    dtt[intersect(row.names(dt)[dt[,1]==0] , DE.g1),1] <-"FN"
    dtt[intersect(row.names(dt)[dt[,1]==-1] , DE.g1),1]<-"FN"
    
    dtt[intersect(row.names(dt)[dt[,1]==1],DE.g1),1]<-"TP"
    dtt[intersect(row.names(dt)[dt[,1]==1], setdiff(row.names(dtt),DE.g1)),1]<-"FP"
    dtt$group1<-factor(dtt$group1, levels = c("TN","FN","TP","FP"))
    
    dtt[intersect(row.names(dt)[dt[,2]==-1] , setdiff(row.names(dtt), DE.g2)),2]<-"TN"
    dtt[intersect(row.names(dt)[dt[,2]==0] , setdiff(row.names(dtt), DE.g2)),2]<-"TN"
    dtt[intersect(row.names(dt)[dt[,2]==0], DE.g2),2] <-"FN"
    dtt[intersect(row.names(dt)[dt[,2]==-1], DE.g2),2]<-"FN"
    
    dtt[intersect(row.names(dt)[dt[,2]==1],DE.g2),2]<-"TP"
    dtt[intersect(row.names(dt)[dt[,2]==1] , setdiff(row.names(dtt), DE.g2)),2]<-"FP"
    dtt$group2<-factor(dtt$group2, levels = c("TN","FN","TP","FP"))
    
    #print(levels(df[, 1]))
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=1, status = dtt[,1], 
                  main = "Group 1 (limma)", 
                  legend = "bottomright",
                  values=c("TN","FN","TP","FP"),
                  hl.col = c("black","orange","steelblue","red"), 
                  hl.cex=c(0.3, 1,1,1))
    
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=2, status = dtt[,2], 
                  main = "Group 2 (limma)", 
                  legend = "bottomright",
                  values=c("TN","FN","TP","FP"),
                  hl.col = c("black","orange","steelblue","red"), 
                  hl.cex=c(0.3, 1,1,1))
    
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    print("Group1 true DE logFC summary")
    print(summary(obs_res$summary.tb[DE.g1, "logFC.g1"]))
    print("Group2 true DE logFC summary")
    print(summary(obs_res$summary.tb[DE.g2, "logFC.g2"]))
    print(boxplot(main = paste(as.character(groups_lst[[cp]]*100), collapse = "vs"),
                  obs_res$summary.tb[DE.g1, "logFC.g1"], 
                  obs_res$summary.tb[DE.g2, "logFC.g2"], 
                  names=c(paste("group1\n(#DE=", length(DE.g1),")", sep=""), 
                          paste("group2\n(#DE=", length(DE.g2),")", sep="")),
                  ylab = "logFC of true DE")
          )
    
    obsNRes<- computeObsMore(counts(sim), factor(sim$Group), statistic= "os.t", 
                             cyclic.normalise = TRUE)
    dt<-limma::decideTests(obsNRes$fit.cont.eb.obs)
    tp.g1<- row.names(obsNRes$fit.cont.eb.obs) %in% DE.g1
    tp.g2<- row.names(obsNRes$fit.cont.eb.obs) %in%  DE.g2
    
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=1, 
                  status =tp.g1, main = "Group1 true DE (normalised)", 
                  legend = "bottomright")
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=2, 
                  status =tp.g2, main = "Group2 true DE (normalised)",
                  legend = "bottomright")

    dtt<- matrix("TN", nrow=nrow(obsNRes$fit.cont.eb.obs), ncol=2)
    dtt<-as.data.frame(dtt)
    row.names(dtt)<-row.names(obsNRes$fit.cont.eb.obs)
    colnames(dtt)<-c("group1","group2")
    
    dtt[intersect(row.names(dt)[dt[,1]==-1], setdiff(row.names(dtt),DE.g1)),1]<-"TN"
    dtt[intersect(row.names(dt)[dt[,1]==0] , setdiff(row.names(dtt),DE.g1)),1]<-"TN"
    dtt[intersect(row.names(dt)[dt[,1]==0] , DE.g1),1] <-"FN"
    dtt[intersect(row.names(dt)[dt[,1]==-1] , DE.g1),1]<-"FN"
    
    dtt[intersect(row.names(dt)[dt[,1]==1],DE.g1),1]<-"TP"
    dtt[intersect(row.names(dt)[dt[,1]==1], setdiff(row.names(dtt),DE.g1)),1]<-"FP"
    dtt$group1<-factor(dtt$group1, levels = c("TN","FN","TP","FP"))
    
    dtt[intersect(row.names(dt)[dt[,2]==-1] , setdiff(row.names(dtt), DE.g2)),2]<-"TN"
    dtt[intersect(row.names(dt)[dt[,2]==0] , setdiff(row.names(dtt), DE.g2)),2]<-"TN"
    dtt[intersect(row.names(dt)[dt[,2]==0], DE.g2),2] <-"FN"
    dtt[intersect(row.names(dt)[dt[,2]==-1], DE.g2),2]<-"FN"
    
    dtt[intersect(row.names(dt)[dt[,2]==1],DE.g2),2]<-"TP"
    dtt[intersect(row.names(dt)[dt[,2]==1] , setdiff(row.names(dtt), DE.g2)),2]<-"FP"
    dtt$group2<-factor(dtt$group2, levels = c("TN","FN","TP","FP"))
    
    #print(levels(df[, 1]))
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=1, status = dtt[,1], 
                  main = "Group 1 (limma)", 
                  legend = "bottomright",
                  values=c("TN","FN","TP","FP"),
                  hl.col = c("black","orange","steelblue","red"), 
                  hl.cex=c(0.3, 1,1,1))
    
    limma::plotMA(obsNRes$fit.cont.eb.obs, coef=2, status = dtt[,2], 
                  main = "Group 2 (limma)", 
                  legend = "bottomright",
                  values=c("TN","FN","TP","FP"),
                  hl.col = c("black","orange","steelblue","red"), 
                  hl.cex=c(0.3, 1,1,1))
    
    dev.off()
  }
}

x<-rpois(20,2)
y<-rpois(15,2)
df<-data.frame(X=c(x,y),Grp=rep(c("x","y"),times=c(20,15)))
df
```






```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )

# 1:20 runs -> 20run_7cp_g22098
# set.seed(22098)
# rep.times<-20
# rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+8900, 
#                         size = length(groups_lst), replace = FALSE)
# 20:50 runs -> 30run_7cp_g23098
#set.seed(23098)
#rep.times<-30
#rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+93, 
#                         size = length(groups_lst), replace = FALSE)
set.seed(23098)
rep.times<-30
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)

# rm(adj.p, adj.df)
tic.clearlog()
tic(paste(rep.times, "repeated rounds total time"))
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+ 93, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("repeated round", rep, "started"))
  tic(paste("repeated round", rep, "time"))
  for (cp in 1:length(groups_lst)){
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    
    ############################################################################
    # QC 
    # remove lowly expressed genes 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    
    # check the logFC for each gene 
    obs_res<- computeObs(counts(sim), factor(sim$Group), statistic= "os.t")
    DE.g1<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1]
    DE.g2<- row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]
    
    neglogFC.DEs <- c(intersect(DE.g1, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g1<0]),
                      intersect(DE.g2, row.names(obs_res$summary.tb)[obs_res$summary.tb$logFC.g2<0])
    )
    # remove true DEs with negative logFC
    if (length(neglogFC.DEs)>0) {
      sim<- sim[-match(neglogFC.DEs, row.names(sim)), ]
    }
    message(paste("simulated data dimension:",paste(as.character(dim(sim)), collapse = ", ")))
    
    # set the identifier for the plots 
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    
    ############################################################################
    # run permutation for all stats
    n.cores=parallel::detectCores()-8
    if (cp == 1){
      perm.size = 10000
    }else{
      perm.size = 4000
    }
    
    #setwd("~/Desktop/Data Science Research Project/MDSresearchproject/50run_7cp/20run_7cp_g22098")
    setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/50run_7cp/30run_7cp_g23098")
    os.treatt.res<- readRDS(paste(prefix, "os.treatt.Rds", sep="."))
    ############################################################################
    # creat the result table 
    #stat.lst<- c("os.t","os.treatt", "lfc.p","ts.modt", "os.modt")
    logFC.vals<- c(0.02, 0.05,0.1, 0.2, 0.4, 0.6, 0.8)
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","F1","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic","logFC.val")
      adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    auc.values <- plotComparison(sim, perm.size = perm.size,
                                 plt.main = paste(prefix,"os.treatt.res","pdf", sep="."), 
                                 result=os.treatt.res)
    logFC.df<- as.data.frame(cbind(os.treatt.res$result.table[[1]][, 2],
                                   os.treatt.res$result.table[[2]][, 2]))
    row.names(logFC.df)<-row.names(os.treatt.res$obs.stat)
    colnames(logFC.df)<-c("logFC.g1","logFC.g2")
    trueDE<-os.treatt.res$true.upreg
    for (i in 1:length(logFC.vals)){

      trueDE = list(intersect(row.names(logFC.df[logFC.df$logFC.g1 > logFC.vals[i], ]),
                              trueDE[[1]]), 
                    intersect(row.names(logFC.df[logFC.df$logFC.g2 > logFC.vals[i], ]),
                              trueDE[[2]]))
      adj.df<-computeSummary3simple(os.treatt.res$obs.pval.adj, os.treatt.res$perm.pval.adj,
                                    adj = "adjusted",
                                    true.upreg = trueDE, 
                                    cell_num=as.vector(table(sim$Group)), 
                                    main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                                    seed.number=rep.seed[cp],perm.size=perm.size,
                                    logFC.df=logFC.df,logFC.cutoff = logFC.vals[i],
                                    auc.values=auc.values, statistic = "os.treatt", 
                                    combined=FALSE)
      adj.df$logFC.val<-logFC.vals[i]
      adj.p<- rbind(adj.p, adj.df)
      }
    
  }
  print(paste("round", rep,"finished"))
  toc(log = T)
}
toc(log = T)
saveRDS(adj.p, "tt_3lfc.Rds")
#adj.p$statistic<-gsub(".res","", adj.p$statistic)
adj.p$group<- factor(adj.p$group)
adj.p[adj.p$statistic=="lfc.p"&adj.p$test.name=="limma","statistic"]<-"os.t"

adj.p[adj.p$TP==0,"precision"]<-0
adj.p[adj.p$TP==0,"sensitivity"]<-0
adj.p[adj.p$TP==0,"F1"]<-0

adj.p$group <- factor(adj.p$group,levels = as.vector(unique(adj.p$group)))
adj.p$category <- paste(adj.p$test.name, adj.p$statistic)
gr<- unlist(groups_lst)*100

# combined=FALSE
cp.ft<-as.vector(rep(tapply(gr, as.character(gl(length(gr), 2, length(gr))),   
                                FUN= paste, collapse='% : '), 1))
adj.p$cp<- rep(paste("#group1 : #group2 = ",paste(cp.ft, "%",sep=""), sep=""),times=50,each = 28)
adj.p$cp<-factor(adj.p$cp, 
                 levels = c("#group1 : #group2 = 1% : 99%",
                            "#group1 : #group2 = 5% : 95%",
                            "#group1 : #group2 = 10% : 90%",
                            "#group1 : #group2 = 20% : 80%",
                            "#group1 : #group2 = 30% : 70%",
                            "#group1 : #group2 = 40% : 60%",
                            "#group1 : #group2 = 50% : 50%")
                 )

adj.p$logFC.val<-as.factor(adj.p$logFC.val)
df<-adj.p[adj.p$cp %in% cps[c(2,7)], ]
#clrs<-c("lightskyblue1","lightskyblue2","steelblue1","steelblue2","steelblue3","steelblue4",
#        "orange1","orange2","tan1","tan2","tan3", "tan4")
clrs<-c("lightskyblue2","tan2")
sensitivity<-ggplot(data = df, 
                    aes(x = factor(logFC.val), y = sensitivity,fill = factor(category)))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, ncol =2))+
 # xlab("logFC threshold value")+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0.5,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)

ggsave("sensitivity.pdf", width = 20, height=8)

precision<-ggplot(data = df, 
                    aes(x = factor(logFC.val), y = precision,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, ncol =2))+
  ylab("precision")+ 
  scale_y_continuous(limits=c(0.7,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)
ggsave("precision.pdf", width = 20, height=8)

f1<-ggplot(data = df, aes(x = factor(logFC.val), y = F1,fill = category))+
  geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        axis.title.y=element_text(size=20), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=2, ncol =length(clrs)/2))+
  xlab("logFC threshold value")+
  ylab("F1 score")+ 
  scale_y_continuous(limits=c(0.65,1), oob = rescale_none)+
  scale_fill_manual(values=clrs)
ggsave("f1.pdf", width = 20, height=8)
ggarrange(precision, sensitivity, f1, heights = c(3,3,3), ncol = 1,  nrow = 3,
          legend="top", common.legend = T,align="hv")
ggsave(paste("tt.varythreshold", "pdf",sep="."), width = 12, height=8)
```







#######################################
(code chunk A) repeted version I of the second code chunk
```{r}
groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )

perm.size = 4000
set.seed(12202)
rep.times<-5
seed.number.cp <- sample(x = 100:10000, size = rep.times, replace = FALSE)
#for (rep in 1: rep.times){
# set.seed(seed.number.cp[rep])
#  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+8900, 
#                          size = length(groups_lst), replace = FALSE)
##  for (cp in 1:length(groups_lst)){
#    print(rep.seed[cp])
#  }
#  print(paste("round", rep,"finished"))
  
#}
# rm(adj.p, adj.df, raw.p, raw.df)
for (rep in 1: rep.times){
  set.seed(seed.number.cp[rep])
  rep.seed <- sample(x = seed.number.cp[rep]:seed.number.cp[rep]+8900, 
                         size = length(groups_lst), replace = FALSE)
  print(paste("round", rep,"started"))
  for (cp in 1:length(groups_lst)){
    #rep.seed[cp]
    #setwd("~/Desktop/Data Science Research Project/MDSresearchproject/different_cp_stat/global_seed_7654")
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1,1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
    )
    
    #sim <- logNormCounts(sim)
    #sim <- runPCA(sim)
    #plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
    #  theme(plot.title = element_text(size = 20, face = "bold"))
    
    # number of zeros each gene have 
    numzero.genes <- rowSums(counts(sim)==0)
    keep.genes <- numzero.genes < (ncol(counts(sim))-min(groups_lst[[cp]][1]*1000, 100))
    keep.genes <- setdiff(row.names(sim)[keep.genes],
                          intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                    row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
    sim<- sim[keep.genes, ]
    #print(dim(sim))
    
    prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
    
    n.cores=parallel::detectCores()-8
    os.t.res<- runComparison(sim, perm.size, statistic = "os.t", n.cores = n.cores)
    os.treatt.res<- runComparison(sim, perm.size, statistic = "os.treatt", n.cores = n.cores)
    lfc.p.res<- runComparison(sim, perm.size, statistic = "lfc.p", n.cores = n.cores)
    os.modt.res<- runComparison(sim, perm.size, statistic = "os.modt", n.cores = n.cores)
    ts.modt.res<- runComparison(sim, perm.size, statistic = "ts.modt", n.cores = n.cores)
    saveRDS(os.t.res, paste(prefix, "os.t.res.Rds", sep="."))
    saveRDS(os.treatt.res, paste(prefix, "os.treatt.Rds", sep="."))
    saveRDS(lfc.p.res, paste(prefix, "lfc.p.Rds", sep="."))
    saveRDS(ts.modt.res, paste(prefix, "ts.modt.Rds", sep="."))
    #os.t.res<-readRDS(paste(cp, "os.t.res.Rds", collapse="."))
    #os.treatt.res<-readRDS(paste(cp, "os.treatt.Rds", collapse="."))
    #lfc.p.res<-readRDS(paste(cp, "lfc.p.Rds", collapse="."))
    stat.lst<- c("os.t","os.treatt", "lfc.p","ts.modt")
    res.lst<- list(os.t.res, os.treatt.res,lfc.p.res, ts.modt.res)
    
    if (exists("adj.df") == FALSE ){
      cols.n<- c("group","cell.type","num.cells", "test.name", "num.true.upreg","num.upreg",
                 "TP", "precision", "sensitivity","overlap","TP.overlap","cutoff","perm.size",
                 "seed.number","AUC","statistic")
      raw.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)), cols.n)
      adj.p<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    for (a in 1:length(stat.lst)){
      auc.values <- plotComparison(sim, perm.size = perm.size, seed.n = rep.seed[cp], 
                                   result=res.lst[[a]])
      raw.df<-computeSummary3(res.lst[[a]]$obs.pval, res.lst[[a]]$perm.pval,
                              adj = "",
                              true.upreg = res.lst[[a]]$true.upreg, 
                              cell_num = as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size, 
                              auc.values=auc.values, statistic = stat.lst[[a]])
      
      adj.df<-computeSummary3(res.lst[[a]]$obs.pval.adj, res.lst[[a]]$perm.pval.adj,
                              adj = "adjusted",
                              true.upreg = res.lst[[a]]$true.upreg, 
                              cell_num=as.vector(table(sim$Group)), 
                              main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                              seed.number=rep.seed[cp],perm.size=perm.size,
                              auc.values=auc.values, statistic = stat.lst[[a]])
      raw.p<- rbind(raw.p, raw.df)
      adj.p<- rbind(adj.p, adj.df)
    }
    
  }
  print(paste("round", rep,"finished"))
}
```


```{r}
for (cp in 1:length(groups_lst)){
    #rep.seed[cp]
    #setwd("~/Desktop/Data Science Research Project/MDSresearchproject/different_cp_stat/global_seed_7654")
    sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                         batchCells = 1000, dropout.type = "none", out.prob = 0, 
                         de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                         group.prob = groups_lst[[cp]],
                         #seed = seed.number.cp[cp], 
                         seed = rep.seed[cp], 
                         de.facLoc = c(1.1, 1.1),
                         de.facScale = c(0.5, 0.5),
                         verbose = FALSE
                         )
    
    sim <- logNormCounts(sim)
    sim <- runPCA(sim)
     prefix<-paste("s",rep.seed[cp], paste(as.character(table(sim$Group)),collapse="_"), sep="_")
     pdf(paste(prefix, "pdf", sep="."))
    plot(plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
      theme(plot.title = element_text(size = 20, face = "bold")))
    dev.off()
}
```

backup plot codes
```{r}
sensitivity<-ggplot(data = adj.p.tt, 
       aes(x = factor(category), y = sensitivity,fill = category))+
  
  #geom_bar(width=0.65, stat="identity",color="black", position=position_dodge())+
  #geom_jitter(position=position_jitter(0.4))+
  #geom_point(position=position_jitterdodge(0.6))+
  #geom_dotplot(binaxis = "y", stackgroups = TRUE,  method = "histodot")+
  #geom_point(position=position_jitterdodge(dodge.width=0.1)) +
  geom_boxplot(size=0.2, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
             size=0.4, color = "black", alpha=0.9)+
  
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top", #legend.text=element_text(),
        #legend.spacing.x = unit(0.6, 'cm'),
        legend.text=element_text(margin=margin(r=0.6,unit="cm"),size=18))+
  guides(fill = guide_legend(ncol = 9))+
  #xlab("")+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0, 1), oob = rescale_none)+
  scale_fill_manual(values=c("steelblue2","darkgoldenrod1"))
ggsave("sensitivity.pdf", width = 18, height=6)
precision<-ggplot(data = adj.p.rest, 
       aes(x = factor(category), y = precision,fill = category))+
  geom_boxplot(size=0.2, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
             size=0.4, color = "black", alpha=0.9)+
  
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
   theme(axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top", 
        legend.text=element_text(margin=margin(r=0.6,unit="cm"),size=18))+
  guides(fill = guide_legend(ncol = 9))+
  #xlab("")+
  ylab("precision")+ 
  scale_y_continuous(limits=c(0, 1), oob = rescale_none)+
  scale_fill_manual(values=c('lightsteelblue2','navajowhite2',
                              "steelblue2","darkgoldenrod1",
                              "royalblue1","coral","blue4","tomato3",
                              "green4"))
ggsave("precision.pdf", width = 18, height=6)

f1<-ggplot(data = adj.p, 
       aes(x = factor(category), y = F1,fill = category))+
  geom_boxplot(size=0.2, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=3, jitter.height=0), 
             size=0.4, color = "black", alpha=0.9)+
  facet_grid(cell.type~cp, scales='free_x', space='free_x')+
  theme(axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        axis.ticks.x=element_blank(), 
        axis.text.x.bottom =element_blank(), 
        axis.title.x=element_blank(),
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top", 
        legend.text=element_text(margin=margin(r=0.5,unit="cm"),size=14))+
  guides(fill = guide_legend(ncol = 9))+
  #xlab("")+
  ylab("F1 score")+ 
  scale_y_continuous(limits=c(0, 1), oob = rescale_none)+
  scale_fill_manual(values=c('lightsteelblue2','navajowhite2',
                              "steelblue2","darkgoldenrod1",
                              "royalblue1","coral","blue4","tomato3",
                              "green4"))
ggsave("F1.pdf", width = 18, height=6)


ggarrange(precision, sensitivity, heights = c(3,3), ncol = 1,  nrow = 2,
          legend="top", common.legend = T)
ggsave("simulation_result.pdf", width = 23, height=12)


```

```{r}

```

