---
title: "R Notebook"
output: html_notebook
---
```{r}

library(Seurat)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(splatter)
library(reshape2)
library(pROC)
library(ggforce) 

pbmc.data<- readRDS("pbmc_pooled_sex.Rds")
cm<- pbmc.data@assays$RNA@counts
table(pbmc.data$individual)

#subset_ind<- c("685_686", "689_690","691_692")
#cm<- pbmc.data[, pbmc.data$individual %in% subset_ind ]@assays$RNA@counts
cm<- pbmc.data[, pbmc.data$individual == "689_690"]@assays$RNA@counts
dim(cm) # 32738  3402 (1789+1613) $32738  4907

pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)


cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]
ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep


# with one cell type from one individual
selected_cells <- colnames(cm.processed[,pbmc.data[,colnames(cm.processed)]$predicted.celltype.l1 =="CD4 T"])
cm.processed.r<- cm.processed[, match(selected_cells, colnames(cm.processed))]
metadata <- data.frame(cell_type = pbmc.data[row.names(cm.processed.r),colnames(cm.processed.r)]$predicted.celltype.l1,
                       ind = '689_690')

#sce <- SingleCellExperiment(assays = as.matrix(cm.processed.r),
#                            colData=metadata)

sce <- SingleCellExperiment(list(counts=as.matrix(cm.processed.r)),colData=metadata)


curr_params <- newSplatParams()
# params <- setParam(params, "group.prob", ct_prop)
curr_params <- splatEstimate(sce,params = curr_params)

```


```{r}

perm.size = 100000


sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                     batchCells = 1000, dropout.type = "none", out.prob = 0, 
                     de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                     group.prob = c(0.1, 0.9),
                     seed = 336, 
                     de.facLoc = c(0.5, 0.5),
                     de.facScale = c(0.1,0.1),
                     verbose = FALSE)
numzero.genes <- rowSums(counts(sim)==0)
keep.genes <- numzero.genes < (ncol(counts(sim))-10)
keep.genes <- setdiff(row.names(sim)[keep.genes],
                      intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
sim<- sim[keep.genes, ]
result<- runComparison(sim, perm.size)
saveRDS(result$t.perm.array, "t.perm.array.Rds")
saveRDS(result$obs.stat,"obs.tstat.Rds")
saveRDS(result$df.list[[1]], "group1Table.Rds")
saveRDS(result$df.list[[2]], "group2Table.Rds")

auc.values <- plotComparison(sim, perm.size = perm.size, seed.n = 336, result=result.new,
                             plotMA= TRUE, plotROC = TRUE, plotCumsum = TRUE)
raw.df<-computeSummary3(result$obs.pval, result$perm.pval,
                        adj = "",
                        true.upreg = result$true.upreg, 
                        cell_num = as.vector(table(sim$Group)), 
                        main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                        seed.number=seed.number.cp[m],perm.size=perm.size, auc.values=auc.values)

adj.df<-computeSummary3(result$obs.pval.adj, result$perm.pval.adj,
                        adj = "adjusted",
                        true.upreg = result$true.upreg, 
                        cell_num=as.vector(table(sim$Group)), 
                        main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                        seed.number=seed.number.cp[m],perm.size=perm.size,auc.values=auc.values)

computeSummary3(obs.pval, perm.pval,
                        adj = "",
                        true.upreg = true.upreg, 
                        cell_num = as.vector(table(sim$Group)), 
                        main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                        seed.number=seed.number.cp[m],perm.size=perm.size, auc.values=auc.values)


```


```{r}
# note the precomputed t.perm.array 
t.perm.array<- readRDS("cp1090_loc05scale01_100k/t.perm.array.Rds")
obs.tstat<- readRDS("cp1090_loc05scale01_100k/obs.tstat.Rds")
group1.df<- readRDS("cp1090_loc05scale01_100k/group1Table.Rds")
group2.df<- readRDS("cp1090_loc05scale01_100k/group2Table.Rds")


group1.df
summary(group1.df$perm.raw.pvalue)

table(group1.df$perm.raw.pvalue == min(group1.df$perm.raw.pvalue))

summary(group2.df$perm.raw.pvalue)

table(group2.df$perm.raw.pvalue == min(group2.df$perm.raw.pvalue))

table(group1.df$limma.raw.pvalue < 0.00001) # 32 in group1 
table(group2.df$limma.raw.pvalue < 0.00001) # 21 in group1 
group1.df[group1.df$limma.raw.pvalue < 0.00001, "limma.raw.pvalue"]
group2.df[group2.df$limma.raw.pvalue < 0.00001, "limma.raw.pvalue"]

table(row.names(group1.df[group1.df$limma.raw.pvalue < 0.00001, ])%in%
        row.names(group1.df[group1.df$perm.raw.pvalue < 0.00001, ]))


```

```{r}
perm.size = 2000


sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                     batchCells = 1000, dropout.type = "none", out.prob = 0, 
                     de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                     group.prob = c(0.2, 0.8),
                     seed = 336, 
                     de.facLoc = c(0.5, 0.5),
                     de.facScale = c(0.1,0.1),
                     verbose = FALSE)
numzero.genes <- rowSums(counts(sim)==0)
keep.genes <- numzero.genes < (ncol(counts(sim))-10)
keep.genes <- setdiff(row.names(sim)[keep.genes],
                      intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
sim<- sim[keep.genes, ]
result<- runComparison(sim, perm.size)


auc.values <- plotComparison(sim, perm.size = perm.size, seed.n = 336, result=result,
                             plotMA= TRUE, plotROC = TRUE, plotCumsum = TRUE)
raw.df<-computeSummary3(result$obs.pval, result$perm.pval,
                        adj = "",
                        true.upreg = result$true.upreg, 
                        cell_num = as.vector(table(sim$Group)), 
                        main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                        seed.number=336, perm.size=perm.size, auc.values=auc.values)

adj.df<-computeSummary3(result$obs.pval.adj, result$perm.pval.adj,
                        adj = "adjusted",
                        true.upreg = result$true.upreg, 
                        cell_num=as.vector(table(sim$Group)), 
                        main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                        seed.number=336,perm.size=perm.size,auc.values=auc.values)




```

