---
title: "R Notebook"
output: html_notebook
---
```{r}

library(Seurat)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(splatter)
library(reshape2)
library(pROC)
library(ggforce) 

pbmc.data<- readRDS("pbmc_pooled_sex.Rds")
cm<- pbmc.data@assays$RNA@counts
table(pbmc.data$individual)

#subset_ind<- c("685_686", "689_690","691_692")
#cm<- pbmc.data[, pbmc.data$individual %in% subset_ind ]@assays$RNA@counts
cm<- pbmc.data[, pbmc.data$individual == "689_690"]@assays$RNA@counts
dim(cm) # 32738  3402 (1789+1613) $32738  4907

pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)


cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]
ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep


# with one cell type from one individual
selected_cells <- colnames(cm.processed[,pbmc.data[,colnames(cm.processed)]$predicted.celltype.l1 =="CD4 T"])
cm.processed.r<- cm.processed[, match(selected_cells, colnames(cm.processed))]
metadata <- data.frame(cell_type = pbmc.data[row.names(cm.processed.r),colnames(cm.processed.r)]$predicted.celltype.l1,
                       ind = '689_690')

#sce <- SingleCellExperiment(assays = as.matrix(cm.processed.r),
#                            colData=metadata)

sce <- SingleCellExperiment(list(counts=as.matrix(cm.processed.r)),colData=metadata)


```

check simulation 
```{r}

# PCA for original CD4T 
# compare plots for real data and simulation 

table(sce$cell_type)
curr_params <- newSplatParams()
# params <- setParam(params, "group.prob", ct_prop)
curr_params <- splatEstimate(sce,params = curr_params)
# SplatParams
sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                     batchCells = 1000, dropout.type = "none", out.prob = 0, 
                     de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                     group.prob = c(0.5, 0.5),
                     seed = 336, 
                     de.facLoc = c(0.5, 0.5),
                     de.facScale = c(0.1,0.1),
                     verbose = FALSE)
 numzero.genes <- rowSums(counts(sim)==0)
  keep.genes <- numzero.genes < (ncol(counts(sim))-10)
  keep.genes <- setdiff(row.names(sim)[keep.genes],
                        intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                  row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
  sim<- sim[keep.genes, ]
  

# median(sim@rowRanges@elementMetadata$DEFacGroup1[sim@rowRanges@elementMetadata$DEFacGroup1>1])


# ggsave("simulated_cd4T_pca.pdf", width = 8, height=6)

 
boxplot(sim@rowRanges@elementMetadata$DEFacGroup1[match(true.sup.g1, row.names(sim))],
        sim@rowRanges@elementMetadata$DEFacGroup2[match(true.sup.g2, row.names(sim))])
  
  
boxplot(sim@rowRanges@elementMetadata$DEFacGroup1[match(true.sup.g1, row.names(sim))],
        sim@rowRanges@elementMetadata$DEFacGroup2[match(true.sup.g2, row.names(sim))])
  



sim <- logNormCounts(sim)
sim <- runPCA(sim)
plotPCA(sim, colour_by = "Group")+ggtitle("simulated CD4T cells")+ 
  theme(plot.title = element_text(size = 20, face = "bold"))

median(sim@rowRanges@elementMetadata$DEFacGroup1[sim@rowRanges@elementMetadata$DEFacGroup1>1])


table(sce$cell_type)
curr_params <- newSplatParams()
# params <- setParam(params, "group.prob", ct_prop)
curr_params <- splatEstimate(sce,params = curr_params)


```




vary logFC, 
de.facScale = c(0.01, 0.05, 0.1,0.5, 1, 1.5, 2)
```{r}

groups_lst<- list(c(0.01, 0.99),
                  c(0.05, 0.95),
                  c(0.1, 0.9),
                  c(0.2, 0.8),
                  c(0.3, 0.7),
                  c(0.4, 0.6),
                  c(0.5, 0.5)
                  )
facScale_lst<- list(c(0.01, 0.01), c(0.05, 0.05), c(0.1, 0.1), c(0.5, 0.5), 
                    c(1,1), c(1.5, 1.5),c(2,2), c(3, 3), c(4, 4),c(5,5))

perm.size = 1000
set.seed(12202)
seed.number.cp <- sample(x = 100:10000, size = length(groups_lst), replace = FALSE) #length(groups_lst))
rep<- 1
r<-1

#for (m in 1:length(groups_lst)){
for (m in 1:1){
  print(m)
  set.seed(seed.number.cp[2])
  seed.number <- sample(x = 80:seed.number.cp[2], size = length(facScale_lst), replace = FALSE)
  for (r in 1:length(facScale_lst)){
  sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                     batchCells = 1000, dropout.type = "none", out.prob = 0, 
                     de.prob = c(0.02, 0.02), de.downProb = c(0, 0),
                     group.prob = groups_lst[[2]],
                     seed = seed.number[r], 
                     de.facLoc = c(0.5,0.5),
                     de.facScale = facScale_lst[[r]], 
                     verbose = FALSE)
  numzero.genes <- rowSums(counts(sim) ==0)
  keep.genes <- numzero.genes < (ncol(counts(sim))-10)
  sim<- sim[keep.genes, ]
  
  
  res <- runComparison(sim, perm.size = perm.size, seed.n = seed.number[r], 
                       plotMA= TRUE, plotROC = TRUE, plotCumsum = TRUE)
  saveRds(res$t.perm.array, "t.perm.array.Rds")
  saveRds(obs.tstat,"obs.tstat.Rds")
  
  if (m == 1 & r == 1){
    df_raw <- res$raw.result
    df_raw_adj<-res$adj.result
  }else{
    df_raw<- rbind(df_raw, res$raw.result)
    df_raw_adj<-rbind(df_raw_adj, res$adj.result)
  }
  }
}
```


100, 000 permutation
```{r}
groups_lst<- list(#c(0.01, 0.99),
                  #c(0.05, 0.95),
                  c(0.1, 0.9),
                  #c(0.2, 0.8),
                  #c(0.3, 0.7),
                  #c(0.4, 0.6),
                  c(0.5, 0.5))
#facScale_lst<- list(c(0.01, 0.01), c(0.05, 0.05), c(0.1, 0.1), c(0.5, 0.5), 
#                    c(1,1), c(1.5, 1.5),c(2,2), c(3, 3), c(4, 4),c(5,5))
perm.size = 100000
set.seed(12202)
seed.number.cp <- sample(x = 100:10000, size = length(groups_lst), replace = FALSE) #length(groups_lst))
rep<- 1
r<-1

for (m in 1:length(groups_lst)){
#for (m in 1:1){
  print(m)
  #set.seed(seed.number.cp[2])
  #seed.number <- sample(x = 80:seed.number.cp[2], size = length(facScale_lst), replace = FALSE)
  #for (r in 1:1){
  sim <- splatSimulate(curr_params, method = "groups", nGenes = 5000,
                     batchCells = 1000, dropout.type = "none", out.prob = 0, 
                     de.prob = c(0.02, 0.02),de.downProb = c(0, 0),
                     group.prob = c(0.1, 0.9),
                     seed = 336, 
                     de.facLoc = c(0.5, 0.5),
                     de.facScale = c(0.1,0.1),
                     verbose = FALSE)
  numzero.genes <- rowSums(counts(sim)==0)
  keep.genes <- numzero.genes < (ncol(counts(sim))-10)
  keep.genes <- setdiff(row.names(sim)[keep.genes],
                        intersect(row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup1 > 1], 
                                  row.names(sim)[sim@rowRanges@elementMetadata$DEFacGroup2 > 1]))
  sim<- sim[keep.genes, ]
  result<- runComparison(sim, perm.size)
  saveRDS(result$t.perm.array, "t.perm.array.Rds")
  saveRDS(result$obs.tstat,"obs.tstat.Rds")
  saveRDS(result$df.list[[1]], "group1Table.Rds")
  saveRDS(result$df.list[[2]], "group2Table.Rds")
  
  auc.values <- plotComparison(sim, perm.size = perm.size, seed.n = seed.number.cp[m], result=result,
                       plotMA= TRUE, plotROC = TRUE, plotCumsum = TRUE)
  raw.df<-computeSummary3(result$obs.t.pval, result$t.perm.pval,
                     adj = "",
                     true.upreg = result$true.upreg, 
                     cell_num = as.vector(table(sim$Group)), 
                     main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                     seed.number=seed.number.cp[m],perm.size=perm.size, auc.values=auc.values)
  
  adj.df<-computeSummary3(result$obs.t.pval.adj, result$t.perm.pval.adj,
                         adj = "adjusted",
                         true.upreg = result$true.upreg, 
                         cell_num=as.vector(table(sim$Group)), 
                         main.describe = paste(as.character(table(sim$Group)),collapse="_"), 
                         seed.number=seed.number.cp[m],perm.size=perm.size,auc.values=auc.values)

  
  if (m == 1 & r == 1){
    df_raw <- res$raw.result
    df_raw_adj<-res$adj.result
  }else{
    df_raw<- rbind(df_raw, res$raw.result)
    df_raw_adj<-rbind(df_raw_adj, res$adj.result)
  }
  #}
}

```

