---
title: "R Notebook"
output: html_notebook
---
```{r}
library(Seurat)
library(dplyr)
library(SingleCellExperiment)
library(scater)
library(splatter)
library(reshape2)
library(ggplot2)
library(pROC)
library(ggforce) 
library(org.Hs.eg.db)
library(ggpubr)
library(scales)

setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
pbmc.data<- readRDS("pbmc_pooled_sex.Rds")
cm<- pbmc.data@assays$RNA@counts
inds<- as.vector(names(table(pbmc.data$individual)))
#subset_ind<- c("685_686", "689_690","691_692")

all.ind <- data.frame(individual = pbmc.data$individual)
all.ind$libsize <- 0
all.ind$pz = 0
all.ind$numgenes<- 0
all.ind$individual<- factor(all.ind$individual)
row.names(all.ind)<- colnames(pbmc.data)


for (i in inds){
  curr_cm <- pbmc.data[, pbmc.data$individual ==i ]@assays$RNA@counts
  all.ind[all.ind$individual == i, "libsize"] <- colSums(curr_cm)
  all.ind[all.ind$individual == i, "pz"] <-colMeans(curr_cm==0)
  all.ind[all.ind$individual == i, "numgenes"] <- colSums(curr_cm!=0)
}
#cm<- pbmc.data[, pbmc.data$individual %in% subset_ind ]@assays$RNA@counts
cm<- pbmc.data@assays$RNA@counts
dim(cm) # 32738  3402 (1789+1613) $32738  4907
num.cell.df<-data.frame(matrix(0, nrow=12, ncol=2))
colnames(num.cell.df)<- c("ids","num.cells")
num.cell.df$ids<- inds
for (i in 1:12){
  num.cell.df[i,2] <- ncol(pbmc.data[, pbmc.data$individual == inds[i]]@assays$RNA@counts)
}
num.cell.df<- num.cell.df[order(num.cell.df$num.cells),]
num.cell.df$ids<- factor(num.cell.df$ids, levels = num.cell.df[, "ids"])

 ggplot(data=num.cell.df, aes(x=ids, y=num.cells))+
  geom_bar(#position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=0.8,stat="identity", width=0.7)+
  xlab("individuals")+
  ylab("number of cells")+
  geom_text(aes(label=num.cells), vjust=-0.1, size=3)

ls<-ggplot(data= all.ind, aes(x = libsize, col = individual, group = individual))+ 
  geom_density(show.legend = FALSE)+facet_wrap(~all.ind$individual, nrow=4)+
  ggtitle("Distribution of library sizes")+xlab("")

pz<- ggplot(data= all.ind, aes(x = pz, col = individual, group = individual))+ 
  geom_density(show.legend = FALSE)+facet_wrap(~all.ind$individual, nrow=4)+
  ggtitle("Distribution of proportion of zeroes per cell")+xlab("")

nc<-ggplot(data= all.ind, aes(x = numgenes, col =individual , group = individual))+ 
  geom_density(show.legend = FALSE)+facet_wrap(~all.ind$individual, nrow=4)+
  ggtitle("Distribution of detected genes per cell")+xlab("number of detected genes")+ xlab("")


library(ggpubr)
ggarrange(nc, ls,pz, ncol = 1,  nrow = 3,
          legend="right", align="h" #labels = c("(A)", "(B)","(C)"), 
         # vjust = 1.1#, font.label = list(size=15)
          )
ggsave(paste("Figure 4.1.1", "pdf",sep="."), width = 7, height=15)

setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
#cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
#ann <- AnnotationDbi:::select(org.Hs.eg.db,keys=rownames(pbmc.data),
#                             columns=c("SYMBOL","ENTREZID","GENENAME"),
#                              keytype = "SYMBOL")
#m <- match(rownames(cm),ann$SYMBOL)
#numzero.genes <- rowSums(cm==0)
#keep.genes <- numzero.genes < (ncol(cm)-10)
#all.keep <- cm[keep.genes,]
#ann.keep.all <- ann[keep.genes,]
#cm.processed<- all.keep
#ann <- ann[m,]
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]

ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep


pbmc <- CreateSeuratObject(counts = cm.processed,min.features = 500, 
                           min.cells = 10)
dim(pbmc) #15321 16687
```


```{r}
set.seed(9887)
pbmc <- SCTransform(pbmc, verbose = FALSE)
pbmc <- ScaleData(pbmc, verbose = FALSE)
pbmc <- RunPCA(pbmc, npcs = 50, verbose = FALSE)
ElbowPlot(pbmc,ndims=50)
```

```{r}

pbmc <- FindNeighbors(pbmc, dims = 1:30)
pbmc <- FindClusters(pbmc, resolution = c(0.8,0.9, 1, 1.1, 1.2, 1.3, 1.4))
table(Idents(pbmc))
table(pbmc$SCT_snn_res.1.4)
library(clustree)
clustree(pbmc, prefix = "SCT_snn_res.")
```

```{r}
set.seed(98)
pbmc <- RunTSNE(pbmc, reduction = "pca", dims = 1:30)

#pbmc_new <- RenameIdents(object = pbmc, 
#                               "0" = "CD4+ KLRB1- T cell ",
#                               "1" = "CD4+ KLRB1+ T cell ",
#                               "2" = "CD8+ GNLY+ NKG7+ T cell",
#                               "3" = "CD8+ LTB+ T cell",
#                               "4" = "XCL1- NK",
#                               "5" = "CD8+ T cells",
#                               "6" = "TCL1A+ FCER2+ B cell",
#                               "7" = "Monocyte CD14+ ",
#                               "8" = "CD8+ S100B+ T cell ")
Idents(pbmc)<- pbmc.data[,colnames(pbmc)]$predicted.celltype.l1
#table(pbmc.data[,colnames(pbmc)]$predicted.celltype.l1)
#table(Idents(pbmc))
pdf("Figure4.2.1.pdf")
pbmc <- RunUMAP(pbmc, dims = 1:10)
plot(DimPlot(pbmc, reduction = "tsne",label=TRUE,label.size = 6, repel = TRUE)+
  #ggtitle("all individuals")+
    scale_color_brewer(palette="Set1")
  )
dev.off()


for (i in 1:12){
  #cm.ind<- pbmc.data[, pbmc.data$individual == inds[i]]@assays$RNA@counts
  
  plot(DimPlot(pbmc[,colnames(pbmc.data[, pbmc.data$individual == inds[i]])], 
          reduction = "tsne",label=TRUE,label.size = 6,repel = TRUE)+
         ggtitle(paste("individual: ",inds[i],sep="" ))+
         scale_color_brewer(palette="Set1"))
}

dev.off()

```



```{r}
VlnPlot(pbmc, features = c("MS4A1", "CD79A"))
VlnPlot(pbmc,features = perm_sig_limma_nonsig[1:10])
perm_sig_limma_nonsig<-c("MS4A1", "CD79A")


FeaturePlot(pbmc, features = perm_sig_limma_nonsig[1:10])

m<- os.t.res$result.table[[4]]
m<- m[order(m$perm.adj.pvalue, -m$logFC.g4),]
perm_sig_limma_nonsig<- row.names(m)[m$permutation.upreg==1 & m$limma.upreg ==0]
FeaturePlot(pbmc, features = perm_sig_limma_nonsig[1:10])
```


```{r}

library(tictoc)
library(foreach)
individuals<- unique(pbmc.data$individual)
#ann.all<- readRDS("allpbmc.Rds")
files<-list("cell_type_category_rna_B-cells_Cell.tsv",
            "blood_cell_category_rna_naive_CD4T_elevated.tsv",
            "blood_cell_category_rna_naive_CD8T_elevated.tsv","",
            "cell_type_category_rna_Monocytes_Cell.tsv")

markers<- list()
unique.markers<- list()
all.ct<- c("B", "CD4 T", "CD8 T", "DC", "Mono", "NK", "other", "other T")
setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
for (i in 1:8){
  if ( i %in% c(1, 2, 3, 5)){
    
  gene.df<- read.table(files[[i]], sep = '\t', header = TRUE)
  print(dim(gene.df))
  markers[[all.ct[i]]]<- gsub(x = c(unlist(gene.df$Gene),unlist(strsplit(gene.df$Gene.synonym, ","))), 
                      pattern=" ", replacement = "")
  unique.markers[[all.ct[i]]]<-gene.df$Gene
    
  }
  #else{
   # markers[[all.ct[i]]]<- ""
  #  unique.markers[[all.ct[i]]]<- ""
  #}
}
for (ind in 1:length(individuals)){
  print(paste( individuals[ind], "=", as.character(unique(cmpbmc.data[, pbmc.data$individual == individuals[ind]]$sex))))
}
setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis")
for (ind in 1:length(individuals)){
  cm<- pbmc.data[, pbmc.data$individual == individuals[ind]]@assays$RNA@counts
  dim(cm) # 32738  3402 (1789+1613) $32738  4907
  pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)
  cm<-pbmc@assays$RNA@counts
  numzero.genes <- rowSums(cm==0)
  keep.genes <- numzero.genes < (ncol(cm)-10)
  all.keep <- cm[keep.genes,]
  ann.keep.all <- ann.all[keep.genes,]
  cm.processed<- all.keep
  groups<-pbmc.data[row.names(cm.processed),colnames(cm.processed)]$predicted.celltype.l1
  table(groups)
  obs<-  computeObservation(cm.processed, factor(groups),statistic="os.t")
  
  setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis")
  
  os.t.res<- readRDS(paste("id_",individuals[ind],"_10kperm_os.t.Rds", sep=""))
pdf(paste("id",individuals[ind],"pvalues","pdf", sep="."))
  for (ct in 1:ncol(obs$obs.pval)){
    hist(os.t.res$obs.pval[,ct],
         main = paste("raw p-values by limma", "-", colnames(os.t.res$obs.pval.adj)[ct],"cells"), 
         xlab  = "raw p-values")
    
    hist(os.t.res$perm.pval[,ct],
         main = paste("raw p-values by permutation", "-", colnames(os.t.res$obs.pval.adj)[ct],"cells"), 
         xlab  = "raw p-values")
    
    hist(os.t.res$obs.pval.adj[,ct],
         main = paste("adjusted p-values by limma", "-", colnames(os.t.res$obs.pval.adj)[ct],"cells"), 
         xlab  = "adjusted p-values")
    
    hist(os.t.res$perm.pval.adj[,ct],
         main = paste("adjusted p-values by permutation", "-", colnames(os.t.res$obs.pval.adj)[ct],"cells"), 
         xlab  = "adjusted p-values")
    
    curr.ct.name=colnames(obs$obs.pval)[ct]
  curr_df<- data.frame(cbind("Amean"=obs$fit.cont.eb.obs$Amean, 
                      "coef"=obs$fit.cont.eb.obs$coefficients[,ct],
                      "trueMarkers"=rep(0, nrow(obs$obs.stat))
                      ))
      curr_df$Amean<-as.numeric(curr_df$Amean)
      curr_df$coef<-as.numeric(curr_df$coef)
      curr_df$trueMarkers<-factor(curr_df$trueMarkers, levels = c(0, 1))
      curr_df$trueMarkers[match(markers[[curr.ct.name]],row.names(obs$obs.pval))]<-1 
      limma.p<- ggplot(data=curr_df,#[curr_df$trueMarkers==1, ], 
                 aes(x =Amean, y=coef, color=trueMarkers, size=trueMarkers, shape=trueMarkers))+
        geom_point(#color="darkgreen", #position=position_jitterdodge(jitter.width=0, jitter.height=0.002), 
                   alpha=0.4)+
        geom_hline(yintercept=0, size=0.5, color = "black" )+
        theme(#axis.text.x = element_blank(), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="none",
       #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15))+
        #guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
        xlab("Average log-expression")+ylab("log-fold-change")+
        ggtitle(paste("Marker genes for", curr.ct.name, "cells",sep=" "))+
        scale_size_manual(values=c(0.01,2))+
        scale_color_manual(values=c("black","red"))+
        scale_shape_manual(values=c(20, 17))+
        xlim(-1.5, 10)+ylim(-1.5, 5)
        ggsave(paste(paste("TrueDE_MAplot", "ind", individuals[ind],"stat_os.t",
                         "ct",curr.ct.name, sep="_"), "pdf", sep="."), width = 5, height=5)
      
      }
  }
```



```{r}
ct.df<-data.frame(matrix(0, nrow=12, ncol = 10))
colnames(ct.df)<- c("ids", "total.num.cells",names(table(pbmc.data[,colnames(pbmc)]$predicted.celltype.l1)))
for (i in 1:12){
  ct.df[i, "ids"]<-individuals[i]
  #cm.ind<- pbmc.data[, pbmc.data$individual == inds[i]]@assays$RNA@counts
  ct.df[i, "total.num.cells"]<- ncol(pbmc.data[, pbmc.data$individual == individuals[i]]@assays$RNA@counts)
  ct<- as.list(table(pbmc.data[,pbmc.data$individual == individuals[i]]$predicted.celltype.l1))
  for (j in 3:10){
    ct.df[i, colnames(ct.df)[j]]<- ifelse(colnames(ct.df)[j] %in% names(ct), 
                                          yes=ct[[colnames(ct.df)[j]]], no=0)
  }
  #freq<- (ct.df[i, 4:11]+1)/(ct.df[i, 2]+8)
  #ct.df[i, "entropy"]<--sum(freq * log2(freq))
  #freq<- as.numeric(ct.df[i, 4:11])/(ct.df[i, 2])
  #ct.df[i, "entropy"]<-entropy(freq, method="ML", unit="log2")
}
ct.df<- ct.df[order(ct.df$total.num.cells),]
ct.df$ids<- factor(ct.df$ids, levels = ct.df$ids)

library(reshape2)

df<- melt(ct.df, id.vars =c("ids","total.num.cells"),
          variable.name = "cell.type", 
          value.name ="cell.type.number")

library(Hmisc)
latex(ct.df, file="")

nums<-ggplot(data=df, aes(x=ids, fill = cell.type, y=cell.type.number, group=ids))+
  geom_bar(width=0.7, stat="identity")+
 # scale_y_continuous(labels = scales::percent)+
  xlab("individuals")+
  ylab("number of cells")+
  scale_fill_brewer(palette="Set1")+
  theme(#legend.title=element_text("aa"),
    axis.text.x  =element_text(size=6), 
        axis.title.x=element_text(size=10, vjust = 0.4),
        axis.title.y=element_text(size=10), 
        panel.spacing = unit(0.5, "lines"))+
  guides(fill=guide_legend(title="cell types",nrow = 4, ncol=2))

  #geom_text(aes(label=num.cells), vjust=-0.1, size=3)
ct.prop<- cbind(ct.df[,1:2], prop.table(as.matrix(ct.df[,3:10]), 1)*100)
df<- melt(ct.prop, id.vars =c("ids","total.num.cells"),
          variable.name = "cell.type", 
          value.name ="cell.type.proportion")

prop<- ggplot(data=df, aes(x=cell.type, fill = ids, y=cell.type.proportion))+
  geom_bar(width=0.7, stat="identity", position=position_dodge())+
 # scale_y_continuous(labels = scales::percent)+
  xlab("cell types")+
  ylab("cell type proportion (%)")+
  scale_fill_brewer(palette="Set3")+
  theme(#legend.title=element_text("aa"),
        axis.title.x=element_text(size=10),
        axis.title.y=element_text(size=10), 
        panel.spacing = unit(0.5, "lines"))+
  guides(fill=guide_legend(title="individuals",nrow = 6, ncol=2))

ct.prop<- cbind(ct.df[,1:2],apply(round(prop.table(as.matrix(ct.df[,3:10]), 1)*100, 3), 
                                  FUN=paste, "%",sep="",MARGIN= c(1,2))
                )

ct.prop
table(pbmc.data$predicted.celltype.l2)
library(ggpubr)
ggarrange(nums, prop,heights = c(3,3), ncol = 1,  nrow = 2,
          legend="right", align="hv", labels = c("(A)", "(B)"), 
          vjust = 1.1, font.label = list(size=15))
ggsave(paste("Figure4.1.2", "pdf",sep="."), width = 8, height=7)
```


## Test statistics: ordinary t, moderated t and logFC*(1-p)
### this result is based on the original dataset (without normalisation)
```{r}
library(tictoc)
library(foreach)
setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
individuals<- unique(pbmc.data$individual)
ann.all<- readRDS("allpbmc.Rds")
files<-list("cell_type_category_rna_B-cells_Cell.tsv",
            "blood_cell_category_rna_naive_CD4T_elevated.tsv",
            "blood_cell_category_rna_naive_CD8T_elevated.tsv","",
            "cell_type_category_rna_Monocytes_Cell.tsv")

markers<- list()
unique.markers<- list()
all.ct<- c("B", "CD4 T", "CD8 T", "DC", "Mono", "NK", "other", "other T")
for (i in 1:8){
  if ( i %in% c(1, 2, 3, 5)){
    
  gene.df<- read.table(files[[i]], sep = '\t', header = TRUE)
  print(dim(gene.df))
  markers[[all.ct[i]]]<- gsub(x = c(unlist(gene.df$Gene),unlist(strsplit(gene.df$Gene.synonym, ","))), 
                      pattern=" ", replacement = "")
  unique.markers[[all.ct[i]]]<-gene.df$Gene
    
  }
  #else{
   # markers[[all.ct[i]]]<- ""
  #  unique.markers[[all.ct[i]]]<- ""
  #}
}

#for (ind in 1:length(individuals)){
for (ind in c(3)){
  cm<- pbmc.data[, pbmc.data$individual == individuals[ind]]@assays$RNA@counts
  dim(cm) # 32738  3402 (1789+1613) $32738  4907
  
  pbmc.ind <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)
  
  cm<-pbmc.ind@assays$RNA@counts
 
  numzero.genes <- rowSums(cm==0)
  keep.genes <- numzero.genes < (ncol(cm)-10)
  all.keep <- cm[keep.genes,]
  ann.keep.all <- ann.all[keep.genes,]
  cm.processed<- all.keep
  dim(cm.processed)
  n.cores=parallel::detectCores()-8
  perm.size = 10000
  groups<-pbmc.data[row.names(cm.processed),colnames(cm.processed)]$predicted.celltype.l1
  table(groups)
  
  #obs<- computeObservation(cm.processed, factor(groups),statistic= "os.t")
  #all.res<- pPermMultipleStatistics(cm.processed, groups, perm.size = perm.size, n.cores=n.cores)
  #os.t.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "os.t",
  #                         n.cores=n.cores, perm.arrays =all.res$os.t.stat )
  #os.mot.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "os.modt",
  #                         n.cores=n.cores, perm.arrays =all.res$os.modt.stat )
  #lfc.p.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "lfc.p",
  #                         n.cores=n.cores, perm.arrays =all.res$lfc.p.stat )
  
  setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis")
  #obs<- computeObservation(cm.processed, factor(groups),statistic= "os.t")
  os.t.res<- readRDS(paste("id_",individuals[ind],"_10kperm_os.t.Rds", sep=""))
  #os.mot.res <- readRDS(paste("id_",individuals[ind],"_10kperm_os.modt.Rds", sep=""))
  #lfc.p.res<- readRDS(paste("id_",individuals[ind],"_10kperm_lfc.p.Rds", sep=""))
  #saveRDS(os.t.res, paste("id_",individuals[ind],"_10kperm_os.t.Rds", sep=""))
  #saveRDS(os.mot.res, paste("id_",individuals[ind],"_10kperm_os.modt.Rds", sep=""))
  #saveRDS(lfc.p.res, paste("id_",individuals[ind],"_10kperm_lfc.p.Rds", sep=""))

  #stats.res<-list(os.t.res,os.mot.res,lfc.p.res ) 
  #stats.name<- c("os.t","os.modt", "lfc.p")
  #showed.name<- c("ordinary.t","moderated.t", "W statistic")
  stats.res<-list(os.t.res) 
  stats.name<- c("os.t")
  showed.name<- c("ordinary.t")
  if (exists("summary.stat") == FALSE ){
    cols.n<- c("id","cell.type","num.cells", "total.num.cells","test.name", 
                       "num.true.marker","num.upreg","TP", "precision", 
                       "sensitivity","F1", "overlap","TP.overlap","pvalue.cutoff",
                       "perm.size", "AUC","statistic")
      summary.res<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
  for (stat in 1:length(stats.res)){
    res<- stats.res[[stat]]
    obs<-  computeObservation(cm.processed, factor(groups),statistic=stats.name[stat])
    
   plt.title<-paste("thesis_summaryplots",individuals[ind],"stat",showed.name[stat], sep="_")
   auc<- summaryPlots(plt.title =plt.title , obs=obs, result= res,markers = markers,
                      statistic=showed.name[stat] )
   #summary.stat<- computeComparison(res$obs.pval.adj, res$perm.pval.adj, 
  #                                     marker.genes=markers, ids = individuals[ind],
  #                                     unique.marker.genes = unique.markers, 
  #                           cell_num=as.vector(table(groups)), 
  #                           perm.size=10000, auc.values=auc,
  #                           statistic=stats.name[stat])
   #summary.res<- rbind(summary.res, summary.stat)
   
   
   #raw.plt.title<-paste("Rawsummaryplots",individuals[ind],"stat",showed.name[stat], sep="_")
   #rawSummaryPlots(plt.title =raw.plt.title , obs=obs, result= res,markers = markers,
  #                    statistic=showed.name[stat] )
   
  }
  
}

setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis")
saveRDS(summary.res, "summary.res.12ind.Rds")


```




## Test statistics: ordinary t, moderated t and logFC*(1-p)
### this result is based on the cyclic loess normalised dataset
```{r}
library(tictoc)
library(foreach)
setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
individuals<- unique(pbmc.data$individual)
ann.all<- readRDS("allpbmc.Rds")
files<-list("cell_type_category_rna_B-cells_Cell.tsv",
            "blood_cell_category_rna_naive_CD4T_elevated.tsv",
            "blood_cell_category_rna_naive_CD8T_elevated.tsv","",
            "cell_type_category_rna_Monocytes_Cell.tsv")

markers<- list()
unique.markers<- list()
all.ct<- c("B", "CD4 T", "CD8 T", "DC", "Mono", "NK", "other", "other T")
for (i in 1:8){
  if ( i %in% c(1, 2, 3, 5)){
    
  gene.df<- read.table(files[[i]], sep = '\t', header = TRUE)
  print(dim(gene.df))
  markers[[all.ct[i]]]<- gsub(x = c(unlist(gene.df$Gene),unlist(strsplit(gene.df$Gene.synonym, ","))), 
                      pattern=" ", replacement = "")
  unique.markers[[all.ct[i]]]<-gene.df$Gene
    
  }
  #else{
   # markers[[all.ct[i]]]<- ""
  #  unique.markers[[all.ct[i]]]<- ""
  #}
}
 setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis/normalised_v")
#for (ind in 1:length(individuals)){
for (ind in c(3)){
  cm<- pbmc.data[, pbmc.data$individual == individuals[ind]]@assays$RNA@counts
  dim(cm) 
  
  pbmc.ind <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)
  
  cm<-pbmc.ind@assays$RNA@counts
 
  numzero.genes <- rowSums(cm==0)
  keep.genes <- numzero.genes < (ncol(cm)-10)
  all.keep <- cm[keep.genes,]
  ann.keep.all <- ann.all[keep.genes,]
  cm.processed<- all.keep
  dim(cm.processed)
  n.cores=parallel::detectCores()-8
  perm.size = 10000
  groups<-pbmc.data[row.names(cm.processed),colnames(cm.processed)]$predicted.celltype.l1
  table(groups)
  
  #all.res<- pPermMultipleStatistics(cm.processed, groups, perm.size = perm.size, 
  #                                  n.cores=n.cores, normalise = TRUE)
  #os.t.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "os.t",
  #                         n.cores=n.cores, perm.arrays =all.res$os.t.stat, 
  #                         normalise = TRUE )
  #os.mot.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "os.modt",
  #                         n.cores=n.cores, perm.arrays =all.res$os.modt.stat,
  #                         normalise = TRUE )
  #lfc.p.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "lfc.p",
  #                         n.cores=n.cores, perm.arrays =all.res$lfc.p.stat,
  #                         normalise = TRUE )
  
  
  #obs<- computeObservation(cm.processed, factor(groups),statistic= "os.t", normalise = TRUE)

  #cumsumMAPlot(plt.title=paste("id",individuals[ind],"normalised.os.t.cumsumMA","pdf", sep="."),
  #                 res = os.t.res, true.markers = markers, 
  #                 statistic="os.t",
  #                 obs = obs)
      
  
  #saveRDS(os.t.res, paste("id_",individuals[ind],"_10kperm_normalised_os.t.Rds", sep=""))
  #saveRDS(os.mot.res, paste("id_",individuals[ind],"_10kperm_normalised_os.modt.Rds", sep=""))
  #saveRDS(lfc.p.res, paste("id_",individuals[ind],"_10kperm_normalised_lfc.p.Rds", sep=""))

  setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis/normalised_v")
  os.t.res<- readRDS(paste("id_",individuals[ind],"_10kperm_normalised_os.t.Rds", sep=""))
  #os.mot.res<- readRDS(paste("id_",individuals[ind],"_10kperm_normalised_os.modt.Rds", sep=""))
  #lfc.p.res<- readRDS(paste("id_",individuals[ind],"_10kperm_normalised_lfc.p.Rds", sep=""))

  
  #stats.res<-list(os.t.res,os.mot.res,lfc.p.res ) 
  #stats.name<- c("os.t","os.modt", "lfc.p")
  #showed.name<- c("ordinary.t","moderated.t", "W statistic")
  stats.res<-list(os.t.res) 
  stats.name<- c("os.t")
  showed.name<- c("ordinary.t")
  if (exists("summary.stat") == FALSE ){
    cols.n<- c("id","cell.type","num.cells", "total.num.cells","test.name", 
                       "num.true.marker","num.upreg","TP", "precision", 
                       "sensitivity","F1", "overlap","TP.overlap","pvalue.cutoff",
                       "perm.size", "AUC","statistic")
      summary.res<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
  for (stat in 1:length(stats.res)){
    res<- stats.res[[stat]]
    obs<-  computeObservation(cm.processed, factor(groups),
                              statistic=stats.name[stat], normalise = TRUE)
   plt.title<-paste("thesis_normalised_summaryplots",individuals[ind],
                    "stat",showed.name[stat], sep="_")
   auc<- summaryPlots(plt.title =plt.title , obs=obs, result= res,
                      markers = markers,
                      statistic=showed.name[stat] )
   
   # summary.stat<- computeComparison(res$obs.pval.adj, res$perm.pval.adj, 
    #                                   marker.genes=markers, ids = individuals[ind],
    #                                   unique.marker.genes = unique.markers, 
    #                         cell_num=as.vector(table(groups)), 
    #                         perm.size=10000, auc.values=auc,
    #                         statistic=stats.name[stat])
   #summary.res<- rbind(summary.res, summary.stat)
    #raw.plt.title<-paste("normalised_Rawsummaryplots",individuals[ind],"stat",showed.name[stat], sep="_")
    #rawSummaryPlots(plt.title =raw.plt.title , obs=obs, result= res,markers = markers,
    #                  statistic=showed.name[stat] )
  
  }
  
}




```


```{r}
setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis/normalised_v")
saveRDS(summary.res, "summary.res.normalised.12ind.Rds")
#summary.res<- readRDS("summary.res.normalised.12ind.Rds")
summary.res$category<- paste(summary.res$test.name,summary.res$statistic)
summary.res$cell.proportion<- 100*summary.res$num.cells/summary.res$total.num.cells

#setwd("~/Desktop/Data Science Research Project/MDSresearchproject")
#summary.res<- readRDS("summary.res.12ind.Rds")
df2<- summary.res[summary.res$cell.type %in% c("B", "CD4 T", "CD8 T", "Mono"),]

#df2[df2$cell.type == "Mono", "cell.type"]<- "Monocyte"
df2[df2$category=="limma lfc.p" , "category"]<-"limma os.t"

#df2<- df2[df2$category %in% c("limma os.t", "permutation os.t"), ]

df2$cell.type<- factor(df2$cell.type, levels = c("Mono","B", "CD8 T","CD4 T"))
df2$category<- factor(df2$category)
df2$category<- gsub(df2$category, pattern = "os.t", replacement = "ordinary.t")
df2$category<- gsub(df2$category, pattern = "os.modt", replacement = "moderated.t")
df2$category<- factor(df2$category,
                      levels= c("limma ordinary.t","permutation ordinary.t",
                                "limma moderated.t","permutation moderated.t",
                                "permutation lfc.p"))
df2$id<- factor(df2$id, levels=ct.df[, "ids"])

clrs<-c('lightsteelblue2','navajowhite2',
        "steelblue2","darkgoldenrod1","green4")
```


```{r}
# figure 4.3.2
sensitivity<-ggplot(data = df2,#[df2$category=="limma \n os.t", ],
                    aes(x = cell.type, y = sensitivity, color=category))+
  geom_boxplot(size=0.2, width=0.8,outlier.shape = NA, #position = "fill", 
               )+#, position=position_dodge(1))+
  #geom_line()+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=1,  alpha=0.9)+
  #geom_bar(width=0.7, position=position_dodge(),
  #         color="black")+
 # scale_y_continuous(labels = scales::percent)+
  #facet_wrap(~id, nrow=3, ncol=4)+
  theme(#axis.text.x = element_blank(), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=10),
        axis.title.y=element_text(size=10), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(color = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("sensitivity")+ 
  #scale_y_continuous(limits=c(0.5,1), oob = rescale_none)+
  scale_y_continuous(limits=c(0,0.45), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_color_manual(values=clrs)
  # scale_x_discrete(labels=c("limma os.t" = "limma \n ordinary t",
  #                          "permutation os.t" = "permutation \n ordinary t",
  #                          "limma os.modt" = "limma \n moderated t",
  #                           "permutation os.modt" = "permutation \n moderated t"))
precision<-ggplot(data = df2,#[df2$category=="limma \n os.t", ],
                    aes(x = cell.type, y = precision, color=category))+
  geom_boxplot(size=0.2, width=0.8,outlier.shape = NA)+ #position = "fill", )+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=1,  alpha=0.9)+
  theme(legend.title=element_blank(),
        axis.title.x=element_text(size=10),
        axis.title.y=element_text(size=10), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("precision")+ 
  #scale_y_continuous(limits=c(0.5,1), oob = rescale_none)+
  scale_y_continuous(limits=c(0,0.5), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_color_manual(values=clrs)

ggarrange(sensitivity+xlab(""), precision, heights = c(3,3), ncol = 1,  nrow = 2,
          legend="top", common.legend = T,align="hv", labels = c("(A)","(B)"))
ggsave(paste("Figure4.3.2", "pdf",sep="."), width = 13, height=8)

```


```{r}

# figure 4.3.3
sensitivity<-ggplot(data = df2,
                    aes(x = cell.type, y = sensitivity,fill =category))+
  geom_bar(width=0.7, stat="identity", position=position_dodge(), color="black")+
  facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
  theme(legend.title=element_blank(),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.2,unit="cm"), size=13),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0,0.45), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_fill_manual(values=clrs)

precision<-ggplot(data = df2,
                  aes(x = cell.type, y = precision,fill =category))+
  geom_bar(width=0.7, stat="identity",position=position_dodge(), color="black")+
  facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
  theme(legend.title=element_blank(),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.2,unit="cm"), size=13),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("precision")+ 
  scale_y_continuous(limits=c(0,0.5), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_fill_manual(values=clrs)

ggarrange(sensitivity+xlab(""), precision, heights = c(3,3), ncol = 1,  nrow = 2,
          legend="bottom", common.legend = T,align="hv")
ggsave(paste("Figure4.3.3", "pdf",sep="."), width = 12, height=8)

```


```{r}

differ.df<- df2[df2$test.name == "limma",]

differ.df$sensitivity.difference<- df2[df2$test.name == "permutation", "sensitivity"]-df2[df2$test.name == "limma", "sensitivity"]
differ.df$precision.difference<- df2[df2$test.name == "permutation", "precision"]-df2[df2$test.name == "limma", "precision"]

# Figure 4.3.4
sensitivity<-ggplot(data = differ.df, aes(x = num.cells, 
                           y = sensitivity.difference, color=cell.type))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
 # facet_wrap(~statistic,ncol = 3 )+
  geom_smooth(method = "loess", orientation = "x",
              aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=12),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, 4))+
  xlab("number of cells")+
  ylab("gains in sensitivity")
  #scale_y_continuous(limits=c(0,0.5), oob = rescale_none)+
  #scale_color_brewer(palette="Set1")

precision<-ggplot(data = differ.df, aes(x = num.cells, 
                           y = precision.difference, color=cell.type))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
 # facet_wrap(~statistic,ncol = 3 )+
  geom_smooth(method = "loess", orientation = "x",
              aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=12),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1,4))+
  xlab("number of cells")+
  ylab("gains in precision")
  #scale_y_continuous(limits=c(0,0.4), oob = rescale_none)+
  #scale_color_manual(values=clrs)
w<-ggarrange(sensitivity, precision, heights = c(3,3), ncol = 2, 
          nrow = 1, legend="bottom", common.legend = T,align="hv")

annotate_figure(w, top = text_grob("paired difference between limma and permutation",
                                color = "black", face = "bold", size = 15))
ggsave(paste("Figure4.3.4", "pdf",sep="."), width = 10, height=5)
```


```{r}
# figure 4.3.3
sensitivity<-ggplot(data = df2, aes(x = num.cells, 
                           y = sensitivity, color=cell.type,
                           group=test.name))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(#position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
  facet_grid(~test.name)+
  #geom_smooth(method = "loess", orientation = "x",
  #            aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, length(clrs)))+
  xlab("cell type proprotion")+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0,0.5), oob = rescale_none)+
  scale_fill_manual(values=clrs)

precision<-ggplot(data = df2, aes(x = num.cells, 
                           y = precision, color=cell.type,
                           group=test.name))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(#position=position_jitterdodge(jitter.width=0.2, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
  facet_grid(~test.name)+
  geom_smooth(method = "loess", orientation = "x",
              aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, length(clrs)))+
  xlab("cell type proprotion")+
  ylab("precision")+ 
  scale_y_continuous(limits=c(0,0.4), oob = rescale_none)+
  scale_fill_manual(values=clrs)
ggarrange(sensitivity+xlab(""), precision, heights = c(3,3), ncol = 1, 
          nrow = 2, legend="top", common.legend = T,align="hv")
ggsave(paste("Figure 4.3.3", "pdf",sep="."), width = 10, height=8)


ggplot(data = df2, 
       aes(x = id, y= sensitivity,
           fill = cell.type
           #size=entropy
           )
       )+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  #geom_point()+
  geom_bar(#position=position_jitterdodge(jitter.width=0, jitter.height=0), 
            size=0.8,stat="identity", position=position_dodge())+
  facet_grid(cell.type~test.name, 
             #nrow = 2
             )+
  #geom_line(aes(group=cell.type))
  #geom_smooth(method = "glm", orientation = "x",
  #            aes(group=cell.type), se=T)+
  #geom_text(aes(label=paste(round(cell.proportion, 3), "%", sep="")), 
  #          vjust=-0.2,color="black",
  #          position = position_dodge(0.9), size=3)+
  theme(axis.text.x = element_text(angle=90), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=10), 
        axis.title.y=element_text(size=10), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="right",
        #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=10),
        strip.text = element_text(size = rel(1)))+
  #guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
 # xlab("logFC threshold value")+
  ylab("sensitivity")+ 
  scale_y_continuous(limits=c(0,0.45), oob = rescale_none)

legend_size<-c(1,2,3,4,5)

differ.df<- df2[df2$test.name == "limma",]

differ.df$sensitivity.difference<- df2[df2$test.name == "permutation", "sensitivity"]-df2[df2$test.name == "limma", "sensitivity"]
differ.df$precision.difference<- df2[df2$test.name == "permutation", "precision"]-df2[df2$test.name == "limma", "precision"]

# figure 4.3.3
sensitivity<-ggplot(data = differ.df, aes(x = num.cells, 
                           y = sensitivity.difference, color=cell.type))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
  #facet_grid(~test.name)+
  geom_smooth(method = "loess", orientation = "x",
              aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_text(size=15),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1, 4))+
  xlab("number of cells")+
  ylab("sensitivity")
  #scale_y_continuous(limits=c(0,0.5), oob = rescale_none)+
  #scale_color_brewer(palette="Set1")

precision<-ggplot(data = differ.df, aes(x = num.cells, 
                           y = precision.difference, color=cell.type))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
             size=0.2,  alpha=0.9)+
  #geom_line(aes(colour = cell.type))+
  #facet_grid(~test.name)+
  geom_smooth(method = "loess", orientation = "x",
              aes(group=cell.type))+
  theme(#axis.text.x = element_text(angle=90), 
        legend.title=element_text(size=15),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  guides(fill = guide_legend(nrow=1,4))+
  xlab("number of cells")+
  ylab("precision")
  #scale_y_continuous(limits=c(0,0.4), oob = rescale_none)+
  #scale_color_manual(values=clrs)
w<-ggarrange(sensitivity+xlab(""), precision, heights = c(3,3), ncol = 1, 
          nrow = 2, legend="bottom", common.legend = T,align="hv")

annotate_figure(w, 
                top = text_grob("paired difference between limma and permutation",
                                color = "black", face = "bold", size = 14))
ggsave(paste("Figure 4.3.3(paired_differ)", "pdf",sep="."), width = 10, height=5)
```


## Test statistics: treat t 
```{r}
setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis/treatt/")
for (ind in 1:length(individuals)){
#for (ind in 1:7){
  cm<- pbmc.data[, pbmc.data$individual == individuals[ind]]@assays$RNA@counts
  dim(cm) # 32738  3402 (1789+1613) $32738  4907
  
  pbmc.ind <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)
  
  cm<-pbmc.ind@assays$RNA@counts
 
  numzero.genes <- rowSums(cm==0)
  keep.genes <- numzero.genes < (ncol(cm)-10)
  all.keep <- cm[keep.genes,]
  ann.keep.all <- ann.all[keep.genes,]
  cm.processed<- all.keep
  dim(cm.processed)
  n.cores=parallel::detectCores()-8
  perm.size = 10000
  groups<-pbmc.data[row.names(cm.processed),colnames(cm.processed)]$predicted.celltype.l1
  table(groups)
  
  obs<- computeObservation(cm.processed, factor(groups),statistic= "os.treatt", lfc.cutoff = 0.1)
  #all.res<- pPermMultipleStatistics(cm.processed, groups, perm.size = perm.size, n.cores=n.cores)
  treatt.res<- runPermuation(cm.processed, group=groups, perm.size, statistic = "os.treatt",
                           n.cores=n.cores, lfc.cutoff = 0.1)
  
  setwd("/Volumes/Expansion/Data Science Research Project/MDSresearchproject/RealDataAnalysis/treatt/")
  
  #treatt.res <- readRDS(paste("id_",individuals[ind],"_10kperm_treatt_0.01_lfc.Rds", sep=""))

  saveRDS(treatt.res, paste("id_",individuals[ind],"_10kperm_treatt_0.1_lfc.Rds", sep=""))

  stats.res<-treatt.res
  stats.name<- c("treatt")
  showed.name<- c("treat.t")
  if (exists("summary.stat") == FALSE ){
    cols.n<- c("id","cell.type","num.cells", "total.num.cells","test.name", 
                       "num.true.marker","num.upreg","TP", "precision", 
                       "sensitivity","F1", "overlap","TP.overlap","pvalue.cutoff",
                       "perm.size", "AUC","statistic")
      summary.res<- setNames(data.frame(matrix(ncol = length(cols.n), nrow = 0)),cols.n)
    }
    res<- treatt.res
    obs<-  computeObservation(cm.processed, factor(groups),statistic="os.treatt", lfc.cutoff = 0.1)
    summary.stat<- computeComparison(res$obs.pval.adj, res$perm.pval.adj, 
                                       marker.genes=markers, ids = individuals[ind],
                                       unique.marker.genes = unique.markers, 
                             cell_num=as.vector(table(groups)), 
                             perm.size=10000, auc.values=0,
                             statistic="treat.t")
   summary.res<- rbind(summary.res, summary.stat)
    plt.title<-paste("summaryplots",individuals[ind],"treatt_thre0.1", sep="_")
   summaryPlots(plt.title =plt.title , obs=obs, result= res, markers = markers)
}
```



### cell types without true marker genes 
```{r}

summary.res$category<- paste(summary.res$test.name,summary.res$statistic)
summary.res$cell.proportion<- 100*summary.res$num.cells/summary.res$total.num.cells

df2$entropy<- ct.df[match(df2$id,ct.df$ids),"entropy"]
#saveRDS(summary.res, "summary.res.12ind.Rds")
summary.res<- readRDS("summary.res.12ind.Rds")
df3<- summary.res

#df2[df2$cell.type == "Mono", "cell.type"]<- "Monocyte"
df3[df3$category=="limma lfc.p" , "category"]<-"limma os.t"

#df2<- df2[df2$category %in% c("limma os.t", "permutation os.t"), ]

df3$cell.type<- factor(df3$cell.type, 
                       levels = c("DC","other","other T",
                                  "Mono","B","NK","CD8 T","CD4 T")
                       )

df3$category<- factor(df3$category)
df3$category<- gsub(df3$category, pattern = "os.t", replacement = "ordinary.t")
df3$category<- gsub(df3$category, pattern = "os.modt", replacement = "moderated.t")
df3$category<- factor(df3$category,
                      levels= c("limma ordinary.t","permutation ordinary.t",
                                "limma moderated.t","permutation moderated.t",
                                "permutation lfc.p"))



m<-ggplot(data = df3,#[df3$cell.type%in%c("DC","other","other T","NK"), ],
                    aes(x = cell.type, y = num.upreg,
                        fill =category))+
  geom_bar(width=0.7, stat="identity", position=position_dodge())+
  #geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
  #           size=0.2,  alpha=0.9)+
  #geom_line()+
  facet_wrap(~id, nrow=3, ncol=4)+
  #geom_text(aes(label=paste("(",num.cells,")", sep="")), 
  #         color="black",
  #          y = 1100, 
  #          size=3)+
  theme(legend.title=element_blank(),
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        legend.text=element_text(margin=margin(r=0.2,unit="cm"), size=13),
        strip.text = element_text(size = rel(1.3)))+
  #guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("number of detected marker genes")+ 
  scale_fill_manual(values=clrs)
ggsave(paste("Figure 4.3.6", "pdf",sep="."), width = 14, height=5)
```





```{r}



cm<- pbmc.data[, pbmc.data$individual == "689_690"]@assays$RNA@counts
dim(cm) # 32738  3402 (1789+1613) $32738  4907

pbmc <- CreateSeuratObject(counts = cm,min.features = 500, min.cells = 5)

cm<-pbmc@assays$RNA@counts
ann.all<- readRDS("allpbmc.Rds")
numzero.genes <- rowSums(cm==0)
keep.genes <- numzero.genes < (ncol(cm)-10)
all.keep <- cm[keep.genes,]
ann.keep.all <- ann.all[keep.genes,]
cm.processed<- all.keep
dim(cm.processed)
n.cores=parallel::detectCores()-8
perm.size = 20000
groups<-pbmc.data[row.names(cm.processed),colnames(cm.processed)]$predicted.celltype.l1
table(groups)

obs<- computeObservation(cm, factor(groups),statistic= "os.t")

result<- runPermuation(cm, group=groups, perm.size, statistic = "os.t",
                       n.cores=n.cores)


g1<- os.t.res$result.table[[1]]
g2<- os.t.res$result.table[[2]]
g3<- os.t.res$result.table[[3]]
g4<- os.t.res$result.table[[4]]
g5<- os.t.res$result.table[[5]]
g6<- os.t.res$result.table[[6]]
g7<- os.t.res$result.table[[7]]
g8<- os.t.res$result.table[[8]]

table(groups)
dim(g1[g1$permutation.upreg==1 & g1$limma.upreg==1, ])
table(g2$limma.upreg==1)
table(g2$permutation.upreg==1)
limma::plotMA(obs$fit.cont.eb.obs, coef=6, status = g6$limma.upreg, 
                main =  paste("Group 1 (limma )",sep=""), 
                legend = "bottomright",
                #values=c("TN","FN","TP","FP"),
                #hl.col = c("black","orange","steelblue","red"), 
                #hl.cex=c(0.3, 1,1,1)
              )

limma::plotMA(obs$fit.cont.eb.obs, coef=6, 
                main =  paste("Group 1 (permutation )",sep=""), 
                legend = "bottomright",
                #values=c("TN","FN","TP","FP"),
                #hl.col = c("black","orange","steelblue","red"), 
                #hl.cex=c(0.3, 1,1,1)
              )
limma::volcanoplot(obs$fit.cont.eb.obs,coef=3,highlight=10,
                names=row.names(obs$fit.cont.eb.obs), 
                main = paste(colnames(obs$fit.cont.eb.obs)[3],"cells", sep=" "))

fit<- obs$fit.cont.eb.obs
fit$p.value<- g8$perm.adj.pvalue
limma::volcanoplot(fit,coef=2,highlight=10,
                names=row.names(obs$fit.cont.eb.obs), 
                main = paste(colnames(obs$fit.cont.eb.obs)[2],"cells", sep=" "))


dim(g1[g2$permutation.upreg==1 & g2$limma.upreg==1, ])
table(g2$limma.upreg==1)
table(g2$permutation.upreg==1)

df<- as.data.frame(matrix(0, nrow=8, ncol = 5))
colnames(df)<- c("cells","proportion","limma", "permutation", "overlap")
row.names(df)<- colnames(os.t.res$perm.pval)
for ( i in 1:nrow(df)){
  tb<- os.t.res$result.table[[i]]
  df[i, "cells"]<- as.numeric(table(groups)[row.names(df)[i]])
  df[i, "proportion"]<- round(as.numeric(table(groups)[row.names(df)[i]])/length(groups), 5)
  df[i,"limma"]<- sum(tb$limma.upreg == 1)
  df[i,"permutation"]<- sum(tb$permutation.upreg == 1)
  df[i,"overlap"]<- nrow(tb[tb$permutation.upreg == 1 & tb$limma.upreg==1, ])
}
library(limma)
volcanoplot()

boxplot(g2$limma.adj.pvalue)
ggplot(data = g3, aes(y = 1, x =-log10(limma.adj.pvalue), color=-log10(limma.adj.pvalue)))+
  #geom_boxplot( )+
  geom_point(position=position_jitterdodge(jitter.width=0.001, jitter.height=0.001))+
  scale_x_continuous(breaks=seq(0,30,5))+
  xlab("-log10(p-value)")+
  ylab("limma adjusted p-value")+
  scale_y_continuous(breaks=seq(1,1,1), labels=c(""))
  
  
plot(obs$fit.cont.eb.obs$Amean, obs$fit.cont.eb.obs$coefficients[,1], 
     pch=16, cex=0.8, main = paste(colnames(res$obs.pval)[i],"cells",sep=" "))
points(obs$fit.cont.eb.obs$Amean[match(markers[[i]], row.names(res$obs.pval))], 
       obs$fit.cont.eb.obs$coefficients[match(markers[[i]], row.names(res$obs.pval)),1], 
       pch=16, col="steelblue")
points(obs$fit.cont.eb.obs$Amean[match(setdiff(row.names(res$obs.pval)[res$obs.pval[,i]< 0.05], 
                                               markers[[i]]),
                                       row.names(res$obs.pval))], 
       obs$fit.cont.eb.obs$coefficients[match(setdiff(row.names(res$obs.pval)[res$obs.pval[,i]< 0.05], 
                                                      markers[[i]]),
                                              row.names(res$obs.pval)),1], 
       pch=16, col="red")
points(obs$fit.cont.eb.obs$Amean[match(setdiff(markers[[i]], row.names(res$obs.pval)[res$obs.pval[,i]> 0.05]),
                                       row.names(res$obs.pval))], 
       obs$fit.cont.eb.obs$coefficients[match(setdiff(markers[[i]], row.names(res$obs.pval)[res$obs.pval[,i]> 0.05]),
                                              row.names(res$obs.pval)),1], 
       pch=16, col="orange")
abline(h=0)

legend(x = "bottomright",          
       legend = c("TP", "FP", "FN"),
       col = c("steelblue", "red","orange"),           
       lwd = 2)  


CD4Televated_genes<- read.table("blood_cell_category_rna_naive_CD4T_elevated.tsv", sep = '\t', header = TRUE)
CD4Th_elevated_genes<- read.table("blood_cell_category_rna_naive_CD4T_highly_elevated.tsv", sep = '\t', header = TRUE)
perm.DEs<- row.names(g2[g2$permutation.upreg==1, ])
limma.DEs<- row.names(g2[g2$limma.upreg==1, ])  
CD4T.true.DEs<- c(unlist(CD4Televated_genes$Gene),
             unlist(strsplit(CD4Televated_genes$Gene.synonym, " ,")))
(perm.sensitivity = sum(CD4T.true.DEs %in% perm.DEs)/nrow(CD4Televated_genes))
(perm.precision = sum(CD4T.true.DEs %in% perm.DEs)/length(perm.DEs))

(limma.sensitivity = sum(CD4T.true.DEs %in% limma.DEs)/nrow(CD4Televated_genes))
(limma.precision = sum(CD4T.true.DEs %in% limma.DEs)/length(limma.DEs))




CD8Televated_genes<- read.table("blood_cell_category_rna_naive_CD8T_elevated.tsv", sep = '\t', header = TRUE)
CD8Th_elevated_genes<- read.table("blood_cell_category_rna_naive_CD4T_highly_elevated.tsv", sep = '\t', header = TRUE)
perm.DEs<- row.names(g3[g3$permutation.upreg==1, ])
limma.DEs<- row.names(g3[g3$limma.upreg==1, ])  
CD8T.true.DEs<- c(unlist(CD8Televated_genes$Gene),
             unlist(strsplit(CD8Televated_genes$Gene.synonym, " ,")))

(perm.sensitivity = sum(CD8T.true.DEs %in% perm.DEs)/nrow(CD8Televated_genes))
(perm.precision = sum(CD8T.true.DEs %in% perm.DEs)/length(perm.DEs))

(limma.sensitivity = sum(CD8T.true.DEs %in% limma.DEs)/nrow(CD8Televated_genes))
(limma.precision = sum(CD8T.true.DEs %in% limma.DEs)/length(limma.DEs))


Belevated_genes<- read.table("cell_type_category_rna_B-cells_Cell.tsv", sep = '\t', header = TRUE)

perm.DEs<- row.names(g1[g1$permutation.upreg==1, ])
limma.DEs<- row.names(g1[g1$limma.upreg==1, ])  
B.true.DEs<- c(unlist(Belevated_genes$Gene),
             unlist(strsplit(Belevated_genes$Gene.synonym, " ,")))

(perm.sensitivity = sum(B.true.DEs %in% perm.DEs)/nrow(Belevated_genes))
(perm.precision = sum(B.true.DEs %in% perm.DEs)/length(perm.DEs))

(limma.sensitivity = sum(B.true.DEs %in% limma.DEs)/nrow(Belevated_genes))
(limma.precision = sum(B.true.DEs %in% limma.DEs)/length(limma.DEs))



Monoelevated_genes<- read.table("cell_type_category_rna_Monocytes_Cell.tsv", sep = '\t', header = TRUE)

perm.DEs<- row.names(g5[g5$permutation.upreg==1, ])
limma.DEs<- row.names(g5[g5$limma.upreg==1, ])  
Mono.true.DEs<- c(unlist(Monoelevated_genes$Gene),
             unlist(strsplit(Monoelevated_genes$Gene.synonym, " ,")))

(perm.sensitivity = sum(Mono.true.DEs %in% perm.DEs)/nrow(Monoelevated_genes))
(perm.precision = sum(Mono.true.DEs %in% perm.DEs)/length(perm.DEs))

(limma.sensitivity = sum(Mono.true.DEs %in% limma.DEs)/nrow(Monoelevated_genes))
(limma.precision = sum(Mono.true.DEs %in% limma.DEs)/length(limma.DEs))




files<-list("cell_type_category_rna_B-cells_Cell.tsv",
            "blood_cell_category_rna_naive_CD4T_elevated.tsv",
            "blood_cell_category_rna_naive_CD8T_elevated.tsv",
            "cell_type_category_rna_Monocytes_Cell.tsv")

tb.res<- as.data.frame(matrix(0, nrow=4, ncol = 4))
colnames(tb.res)<-c("limma.sensitivity", "perm.sensitivity", "limma.precision", "perm.precision")
obj<- list(g1, g2, g3, g5)
for (i in 1:4){
  gene.df<- read.table(files[[i]], sep = '\t', header = TRUE)
  perm.DEs<- row.names(obj[[i]])[obj[[i]]$permutation.upreg==1 ]
  limma.DEs<- row.names(obj[[i]])[obj[[i]]$limma.upreg==1]  
  true.DEs<- gsub(x = c(unlist(gene.df$Gene),unlist(strsplit(gene.df$Gene.synonym, ","))), 
                  pattern=" ", replacement = "")
  
  perm.sensitivity = round(sum(true.DEs %in% perm.DEs)/nrow(gene.df), 4)
  perm.precision = round(sum(true.DEs %in% perm.DEs)/length(perm.DEs),4)
  
  limma.sensitivity = round(sum(true.DEs %in% limma.DEs)/nrow(gene.df), 4)
  limma.precision = round(sum(true.DEs %in% limma.DEs)/length(limma.DEs),4)
  tb.res[i, 1:4]<-c(limma.sensitivity, perm.sensitivity, limma.precision, perm.precision)
  
}
tb.res




```

```{r}
files<-list("cell_type_category_rna_B-cells_Cell.tsv",
            "blood_cell_category_rna_naive_CD4T_elevated.tsv",
            "blood_cell_category_rna_naive_CD8T_elevated.tsv",
            "cell_type_category_rna_Monocytes_Cell.tsv")
```


```{r}
# figure 4.3.2
sensitivity<-ggplot(data = df2[df2$category %in% c("limma ordinary.t", "permutation ordinary.t"), ],
                    aes(x = cell.type, y = sensitivity,
                        fill =category))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  #geom_line()+
  #geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
  #           size=1,  alpha=0.9)+
  geom_bar(width=0.7, stat="identity", position=position_dodge(), color="black")+
 # scale_y_continuous(labels = scales::percent)+
  facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
  #facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
 #geom_text(mapping = aes(x = cell.type,
 #                         y = 0.41,
#                          #label = paste("(",num.cells,")",
#                          label =num.cells, 
#                          group= category))+
  #geom_text(mapping = aes(x = cell.type,
  #                       y = 0.55,
  #                        #label = paste("(",round(cell.proportion,2),"%)",
  #                        label = paste(round(cell.proportion,2),"%",
  #                                      sep=""), 
  #                        group= category))+
  geom_text(mapping = aes(x = cell.type,
                          y = precision,
                          #label = paste("(",round(num.cells, 1),"%)",
                          label = TP,
                          group= category))+
  theme(#axis.text.x = element_blank(), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.6, "lines"), 
        legend.position="top",
        #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  #guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("sensitivity")+ 
  #scale_y_continuous(limits=c(0.5,1), oob = rescale_none)+
  scale_y_continuous(limits=c(0,0.6), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_fill_manual(values=clrs)
  #scale_x_discrete(labels = tickLlabs)
  #scale_x_discrete(labels=c("limma os.t" = "limma \n ordinary t",
  #                          "permutation os.t" = "permutation \n ordinary t",
  #                          "limma os.modt" = "limma \n moderated t",
  #                           "permutation os.modt" = "permutation \n moderated t"))
#ggsave("precision.pdf", width = 20, height=8)


precision<-ggplot(data = df2[df2$category %in% c("limma ordinary.t", "permutation ordinary.t"), ],
                    aes(x = cell.type, y = precision,
                        fill =category))+
  #geom_boxplot(size=0.2, width=0.8)+#, position=position_dodge(1))+
  #geom_line()+
  #geom_point(position=position_jitterdodge(jitter.width=0, jitter.height=0), 
  #           size=1,  alpha=0.9)+
  geom_bar(width=0.7, stat="identity", position=position_dodge(), color="black")+
 # scale_y_continuous(labels = scales::percent)+
  facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
  #facet_wrap(~id, nrow=3, ncol=4, scales = 'free_x')+
  #geom_text(mapping = aes(x = cell.type,
  #                       y = 0.41,
  #                        #label = paste("(",round(num.cells, 1),"%)",
  #                        label = num.cells,
  #                        group= category))+
  #geom_text(mapping = aes(x = cell.type,
  #                        y = 0.55,
  #                        #label = paste("(",round(num.cells, 1),"%)",
  #                        label = paste(round(cell.proportion,3),"%",
  #                                      sep=""),
  #                        group= category))+
   geom_text(mapping = aes(x = cell.type,
                          y = precision,
                          #label = paste("(",round(num.cells, 1),"%)",
                            label = num.upreg-TP,
                          group= category))+
  theme(#axis.text.x = element_blank(), 
        legend.title=element_blank(),
        #axis.ticks.x=element_blank(), 
        #axis.text.x.bottom =element_blank(), 
        axis.title.x=element_text(size=15),
        axis.title.y=element_text(size=15), 
        panel.spacing = unit(0.5, "lines"), 
        legend.position="top",
        #legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=20),
         legend.text=element_text(margin=margin(r=0.3,unit="cm"), size=15),
        strip.text = element_text(size = rel(1.3)))+
  #guides(fill = guide_legend(nrow=1, ncol =length(clrs)))+
  xlab("cell types")+
  ylab("precision")+ 
  #scale_y_continuous(limits=c(0.5,1), oob = rescale_none)+
  scale_y_continuous(limits=c(0,0.6), oob = rescale_none)+
  #scale_fill_brewer(palette="Set1")
  scale_fill_manual(values=clrs)
  #scale_x_discrete(labels = tickLlabs)
  #scale_x_discrete(labels=c("limma os.t" = "limma \n ordinary t",
  #                          "permutation os.t" = "permutation \n ordinary t",
  #                          "limma os.modt" = "limma \n moderated t",
  #                           "permutation os.modt" = "permutation \n moderated t"))
#ggsave("precision.pdf", width = 20, height=8)

ggarrange(sensitivity+xlab(""), precision, heights = c(3,3), ncol = 1,  nrow = 2,
          legend="top", common.legend = T,align="hv")
ggsave(paste("Figure 4.3.2(cp)", "pdf",sep="."), width = 12, height=8)


```

```{r}
pbmc <- CreateSeuratObject(counts = cm.processed,min.features = 500, min.cells = 10)
dim(pbmc)

FeaturePlot(pbmc, 
            features = c("MS4A1", "GNLY", "CD3E", "CD14", 
                         "FCER1A", "FCGR3A", "LYZ", "PPBP","CD8A"))
```

